### ISSUE TITLE
Intermittent "Access Denied" error in actions2.py

### ISSUE THREAD

**Issue by chilimangoes** [synkarius/caster#100]
After merging the development branch into my local copy, I started getting an occasional Access Denied error on startup, which I traced to [this](https://github.com/synkarius/caster/blob/aae5757ab3292db73e7808cf629a187208204f1f/caster/lib/dfplus/state/actions2.py#L16) line in actions2.py failing:

```
win32gui.SystemParametersInfo(win32con.SPI_SETFOREGROUNDLOCKTIMEOUT, 0, 1)
```

After a little googling, it appears that `SPI_SETFOREGROUNDLOCKTIMEOUT` will fail if [any of the conditions](https://social.msdn.microsoft.com/Forums/vstudio/en-US/09fa16ba-c6ef-410d-bec2-a99a9b9a98d9/issue-with-foregroundlocktimeout-setforegroundwindow) are not true:

- The process is the foreground process.
- The process was started by the foreground process.
- The process received the last input event.
- There is no foreground process.
- The foreground process is being debugged.
- The foreground is not locked (see LockSetForegroundWindow).
- The foreground lock time-out has expired (see SPI_GETFOREGROUNDLOCKTIMEOUT in SystemParametersInfo).
- No menus are active.

It doesn't happen all the time, and I can't identify a pattern to it yet. I'm also not sure what the purpose of that line is or what the impact to the rest of actions2.py is if it fails. For now, I've wrapped it in a try/except so that it won't break the whole start up process.

```
try:
    win32gui.SystemParametersInfo(win32con.SPI_SETFOREGROUNDLOCKTIMEOUT, 0, 1)
except Exception, e:
    print(e)
    print(sys.exc_info()[0])
```

**Comment by synkarius** [comment]
That is [t4ngo's suggested solution](https://code.google.com/p/dragonfly/issues/detail?id=10) to the 64-bit focus window executable problem (which Daanzu fixed). It is no longer necessary and has been commented out in the most recent commit.
