### ISSUE TITLE
"through" command

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#110]
- command which applies (other?) commands across multiple lines
- use a ContextSeeker?
- should work on all IDEs/editors or per IDE/editor
- should take absolute and modulo line numbers
- examples: 
"delete 88 though 92" in modulo mode, if nearest "88" line is 488 deletes 488-492, in absolute mode 88-92

**Comment by Zone22** [comment]
Sweet I was trying to implement something like this in Atom.  

'Select' would be a great command in the context of selecting 'lines' Select 88 though 92"

**Comment by synkarius** [comment]
This is now included in #133, so, closing this issue.
