### ISSUE TITLE
Legion grid uses incorrect screen capture on secondary monitors

### ISSUE THREAD

**Issue by chilimangoes** [synkarius/caster#116]
The Legion command always sends a screen capture the primary monitor to the TiRG DLL, regardless of what monitor your invoking the grid on (e.g. saying "Legion 2").

**Comment by chilimangoes** [comment]
This turned out not to be a simple fix due to a limitation in the PIL ImageGrab.grab() functionality, which cannot grab outside the primary monitor (see [related issue](https://github.com/python-pillow/Pillow/issues/1547) on PIL repo). I proposed a fix on that issue, but it requires modifying the C library PIL depends on, so it's not a simple python patch. I've got some python/ctypes code that I wrote to troubleshoot and test my proposed PIL fixes. I'm going to clean that up and add it to a replacement for `grab()` that we can use.

**Comment by synkarius** [comment]
Hmm. Good find, about PIL. And I'm very much in favor of replacing `grab`. It's the only thing PIL is really required for. Actually, PIL's role in relation to Rainbow Grid is really just cosmetic, so if we can remove it from Legion, we can remove it completely.

**Comment by chilimangoes** [comment]
OK, I'll keep that in mind as I'm working on other grid improvements.
