### ISSUE TITLE
"refresh bring me" disappeared?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#12]
We used to be able to say "refresh bring me" after editing the bringme.toml directly

**Comment by kendonB** [comment]
I presume that the intention is for bring me to automatically reload after a save

**Comment by synkarius** [comment]
No, that's legit. You should be able to use that command still. I think I deleted it because all the selfmod rules were really difficult to convert and I intended to come back to it and put it back in, but then didn't.

**Comment by kendonB** [comment]
Looks like this is fixed now. Thanks!
