### ISSUE TITLE
Improvements to "tie match" and "ex match"

### ISSUE THREAD

**Issue by chilimangoes** [synkarius/caster#125]
Inspired by your comment on #124, I had a couple ideas on how we might improve "tie match" and "ex match" to be a useful addition to "list programs" and the "switch windows" command that I just added.

Assuming we can improve the matching algorithm enough, the first idea would be to auto select the first match rather than presenting the user with a list of Windows - kind of like Google's "I'm feeling lucky" option. The idea is we already have a couple different options for selecting from a list of applications, so this would instead work as a quick way to switch to a specific program, without the trouble of needing multiple commands to get there.

Building on that, if two windows have very similar match scores, we could present the user with a dialogue showing just those windows. For example, if I were to say "ex match chrome" and I had two Chrome windows open, they would both have identical match scores so I would get a dialog box asking which one I wanted to switch to.

We could also have separate commands for showing the full list of matches, the way it works now.

**Comment by synkarius** [comment]
I am very much in favor of this. The "I'm feeling lucky" way was how they originally worked, but the algorithm was never good enough for that.

**Comment by synkarius** [comment]
#154
Symbol Match was cut; this issue is irrelevant.
