### ISSUE TITLE
Symbol Match data trainer

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#127]
- uses BoxActions to pick random words from the directory scanned data and asks the user to pronounce them
- sending back a blank pronunciation causes the BoxActions to stop coming
- all pronounced words become commands
- all pronounced words become data (correct answers) on which to rate the available algorithms, which are used to select symbols when pronunciation is unknown

**Comment by synkarius** [comment]
will help with #49, also possibly can be extended to help with #125

**Comment by chilimangoes** [comment]
Awesome idea. I assume this will also output files in the format you mentioned in #49 that we can submit to use as training data for improving the match algorithm.

**Comment by synkarius** [comment]
Thanks, and yes exactly.

**Comment by synkarius** [comment]
After experimenting with the finished version a bit, I'm questioning the usefulness of turning all the training data into commands automatically. I'm going to leave that part out.

**Comment by synkarius** [comment]
You must have a directory scanned to use this, and then to begin, the command is "'begin symbol training".
