### ISSUE TITLE
Quick access commands for recent symbol matches

### ISSUE THREAD

**Issue by chilimangoes** [synkarius/caster#129]
An idea raised [here](https://github.com/synkarius/caster/issues/49#issuecomment-155274521) to improve usability of symbol matching is to add temporary commands for the N most recent symbol matches. Roughly this would work as follows:

* I say "symbol match test function" and caster presents a list of matches.
* I say "number three" and caster outputs "testfunc" and create a temporary command with the spec "<symbol_recall> test function", where <symbol_recall> is some yet to be determined prefix word.

**Comment by synkarius** [comment]
#154 
Symbol match has been cut; this feature is now irrelevant.
