### ISSUE TITLE
words.txt doesn't seem to work?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#13]
I just plonked my old copy into the `.caster/transformers` folder and it didn't seem to load at all.

**Comment by synkarius** [comment]
So, part of this is that the activation process requires one extra step now, and part of this is that I completely broke the words.txt transformer by allowing it to work on MappingRules in addition to MergeRules.

The additional activation step is setting this in transformers.toml:
```
GlobalDefinitionsRuleTransformer = true
```

I'm fixing the other part now.

**Comment by synkarius** [comment]
That push wasn't a fix. But it does get it to the state where you can activate it and not crash anything. The words.txt transformer is exceptionally hacky and so rather than crashing safely like it should have (and now does until I complete this fix), it unfortunately _didn't_ crash and instead just passed off an unsafe result which crashed out the merge process down the line.

**Comment by synkarius** [comment]
@kendonB That last push ought to fix it. I also renamed the transformer to be more descriptive of what it's doing. So, in transformers.toml, add:
```
TextReplacerTransformer = true
```

**Comment by kendonB** [comment]
This is now working almost perfectly. The one thing I found is that if I included:

```
<<<NOT_SPECS>>>
shin -> shine
```
the whole system breaks with no error message in the window. Does the transformer keep trying to transform this one because it will keep finding "shin" forever?

While we're here and making lots of changes, it might be useful to update the names in this transformer to be more descriptive. For one, the term "spec" is quite opaque to a new user and I think people on gitter have used it to refer to both the spoken command phrase and the spoken command phrase/command action pair. I'm still not 100% sure what the term is supposed to refer to but I'm guessing its the command phrase as written in a rule - i.e. `clear [<nnavi50>]`.

I suggest: 
```
words.txt -> phrase_replacements.txt
ANY -> ANY
SPEC -> COMMAND_PHRASE
EXTRA -> EXTRAS
DEFAULT -> DEFAULTS
NOT_SPECS -> EXTRAS_AND_DEFAULTS
```
@LexiconCode and @Versatilus, do you also have thoughts about this?

**Comment by kendonB** [comment]
I also find that replacing alphabet phrases does not work here. e.g.

```
<<<EXTRA>>>
goof -> gas
```
Doesn't seem to work. Is it because the alphabet phrases are extras via a function (`alphanumeric.get_alphabet_choice`)?

**Comment by kendonB** [comment]
I actually now also find that:
```
<<<SPEC>>>
kick -> ssss
psychic -> shsh
```
breaks the whole system without an error.

**Comment by kendonB** [comment]
However, I find that:
```
<<<SPEC>>>
focus -> look
```
works just fine. This one `focus -> look` makes replacements in the Rstudio rule and for former one makes replacements in Navigation. I wonder why they're different?

**Comment by synkarius** [comment]
@kendonB Look in your rules.toml, at the `_enabled_ordered` list. Is anything in there twice?

**Comment by synkarius** [comment]
@kendonB Regarding terminology, those words are from the Dragonfly source code, and are explained in the docs (although for some reason the image doesn't show up anymore).

https://caster.readthedocs.io/en/latest/readthedocs/Taxonomy_of_a_Rule/
https://github.com/dictation-toolbox/Caster/blob/master/docs/img/terminology.png

In my opinion, renaming them causes two problems:
1) Now you have two names for a thing which used to only have one. People will surely find old discussions and old docs and be confused and you'll have to explain to new people repeatedly that yes, a command phrase and a spec are the same thing.
2) The source code will mismatch.

I'm not going to say it's absolutely not worth renaming them, but you have to weigh those maintenance costs against the decision.

**Comment by synkarius** [comment]
Renaming those things in words.txt seems reasonable. I'm not going to do it, but feel free after this PR goes through.

**Comment by kendonB** [comment]
Here is my: 
```python
_enabled_ordered = ["Alphabet", "Navigation", "Numbers", "Punctuation", "CasterRule", 
  "HardwareRule", "MouseAlternativesRule", "WindowManagementRule", "LegionGridRule",
  "DouglasGridRule", "RainbowGridRule", "HMCRule", "HMCConfirmRule", "HMCDirectoryRule", 
  "HMCHistoryRule", "HMCLaunchRule", "HMCSettingsRule", "DragonRule", "BringRule", 
  "GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule"]
```
 which has no double ups.
This is after:
1. Deleting my .caster
2. switching to the latest ccrmerger2
3. Start dragon
4. Add this:
```
<<<SPEC>>>
kick -> ssss
```
in words.txt
5. put `TextReplacerTransformer = true` in `transformers.toml`
6. Reboot dragon

I was wrong that the whole system doesn't work. It's actually seems like just the `Navigation` rule.

**Comment by kendonB** [comment]
Okay it looks like the Navigation rule is resistant to transformation. I also get the same bug with 

```
<<<SPEC>>>
clear -> bear
```

**Comment by synkarius** [comment]
@kendonB Thank you. That is very helpful, narrowing it down like that. What you've found is very strange, but so far my attempts to rule things out have turned up nothing useful. Onto `Navigation` then! :)

**Comment by kendonB** [comment]
Are you able to reproduce?

**Comment by synkarius** [comment]
Yes, fortunately.

And I'm able to step through these examples in unit tests. But doing so still hasn't turned up anything interesting. All the way up to the point of the RepeatRule getting created, "clear" is properly being replaced by "bear". Unfortunately the old system is nearly impossible to unit test, so I think the next step is to just get remote debugging set back up. That's always such a hassle and I've successfully avoided it up until now, but I'm not seeing what's causing this problem with just the unit tests approach.

Unfortunately, I have to get to sleep now and won't be home until early Sunday, and can't work on this on my (Mac) laptop while I'm away. But, given that this bug exists and one other possibly serious one that I haven't confirmed yet, I am not going to sign off as of tomorrow like I had originally planned. It's going to be tough, but I'll stick around at least until these two bugs are dead and maybe a week or two after that in case anything else related to #385 pops up.

**Comment by kendonB** [comment]
Any help is, of course, much appreciated!

**Comment by kendonB** [comment]
@LexiconCode had mentioned remote debugging at one point in the chat so he may be able to help with setting that up.

**Comment by Versatilus** [comment]
I don't have time before my appointment this afternoon to test it, but I thought I would mention `clear` is both part of a `SPEC` and an `EXTRA`.

That whole file needs cleaned up, IMO.

**Comment by Versatilus** [comment]
I take that back. The command that uses it as an extra also requires a modifier.

Regardless, this all works for me if I nullify the bug mentioned here: https://github.com/synkarius/Caster/commit/8c65be6e2aab9bf2cbff341b93a7967dc8832e8c#commitcomment-35381048

**Comment by synkarius** [comment]
Alright, @kendonB & @Versatilus, give it another shot. I am seeing it work locally now for specs, extras, and defaults.

**Comment by kendonB** [comment]
Looks like it's working correctly now. Great job!
