### ISSUE TITLE
Rainbow for large monitors

### ISSUE THREAD

**Issue by mostlyjason** [synkarius/caster#135]
I recently installed caster on my computer and was excited to try the new rainbow mouse selector. I noticed that when running on a larger monitor the colors loop. Thus if I say "red 86" it will select the first band of red and I won't be able to select anything in the second band of red at the bottom of the screen. I could have fixed this by adding more colors, but I'm worried it would be less intuitive what the names are. Instead, I fixed it by adding more numbers. Now it can go up to 200. You can see my change here https://github.com/mostlyjason/caster/commit/cdaa6267b023f2e0978c6d619e30983120184a32

I didn't submit this is a pull request because I'm concerned it's not generalizable for different sizes of monitors. It would be better to detect the size of the screen and choose an appropriate number. I'm not sure how to do that, so I'm submitting this as an issue.

**Comment by chilimangoes** [comment]
Yeah, I've seen that as well, but I wasn't sure of the best way to fix it. Then I kind of forgot about it since I tend to use Legion grid most of the time. I like your idea of calculating the ideal number of numbers based on the size of the screen and size of the rainbow blocks. Should be pretty simple to do. I'll take a crack at it tomorrow.

**Comment by synkarius** [comment]
The existing solution is, if you want red eighty six in the first red band, 
"red eighty six"
and in the second red band,
"two red eighty six". ("Three red eighty six", etc.)

My original thought was, this way, you don't have to say the word "hundred". But like @chilimangoes, I don't use rainbow grid much, so I don't have a strong preference for how it should work.

**Comment by mostlyjason** [comment]
Ahh I didn't know I could say "two red eighty six". I added documentation on the mouse modes so it's easier for new people to pick up #136

**Comment by synkarius** [comment]
Much appreciated.
