### ISSUE TITLE
Files in default settings.toml come in with both \\ and / for file separation

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#14]
I think they should all use the forward slash as I think it works everywhere?

**Comment by Versatilus** [comment]
This is another item on my short list. I don't think it's much of a problem on the user side of things, but everywhere that we interact with the operating system should have paths pass through `os.path.normpath` first.

**Comment by synkarius** [comment]
Yes, they should all be forward slashes.

**Comment by synkarius** [comment]
You'll have to delete your settings.toml file for this to take effect.

**Comment by synkarius** [comment]
Whoops. Reopening b/c it should be the reporter (@kendonB) who closes it.
