### ISSUE TITLE
Unable to load DLL for legion

### ISSUE THREAD

**Issue by mostlyjason** [synkarius/caster#142]
I'm getting an exception trying to load legion on Windows 10. Specifically, the DLL is not loading. I checked the path and the file is present. Perhaps there are some dependencies its not able to load? For example, I don't have the C++ runtime installed on my computer. Is there any way to recompile this with the /MT flag? I believe this will include dependencies in the DLL. Alternatively, we can include dependencies with the distribution or require users to install them. What do you think is the right solution here? 

> ERROR:action:Exception from function mouse_alternates:
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\actions\action_function.py", line 109, in _execute
>     self._function(**arguments)
>   File "C:\NatLink\NatLink\MacroSystem\caster\lib\navigation.py", line 140, in mouse_alternates
>     ls = LegionScanner()
>   File "C:\NatLink\NatLink\MacroSystem\caster\asynch\mouse\legion.py", line 131, in __init__
>     self.setup_dll()
>   File "C:\NatLink\NatLink\MacroSystem\caster\asynch\mouse\legion.py", line 140, in setup_dll
>     self.tirg_dll = cdll.LoadLibrary(settings.SETTINGS["paths"]["DLL_PATH"] + "tirg-dll.dll")
>   File "C:\Python27\Lib\ctypes\__init__.py", line 443, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Python27\Lib\ctypes\__init__.py", line 365, in __init__
>     self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 126] The specified module could not be found
> ERROR:action.exec:Execution failed: Function(mouse_alternates): [Error 126] The specified module could not be found

As a separate issue, the logger was not initialized at this point in the code so I had to add the following at the top of the file in order to get this error message. 

```
import logging
logging.basicConfig()
```

**Comment by synkarius** [comment]
The source for that dll is here:  https://github.com/synkarius/tirg-dll

**Comment by mostlyjason** [comment]
Great thanks I'll take a look when I get some extra time

**Comment by mostlyjason** [comment]
I found out how to solve this issue. Basically, users need to install the Visual C++ Redistributable Packages for Visual Studio 2013 https://www.microsoft.com/en-us/download/details.aspx?id=40784. MSVCR120.DLL was missing in the distribution and this will add it. 

If we added this DLL in our lib directory, would that prevent users from having to install the redistributable packages? I believe on the site Microsoft says that we are allowed to distribute them with our applications https://www.visualstudio.com/en-us/downloads/2015-redistributables-rc-vs.aspx

**Comment by mostlyjason** [comment]
I tried adding this DLL to the lib directory and it didn't work. The only way I found to get this work is by installing the Visual C++ Redistributable Packages for Visual Studio 2013 x86.

We should probably add this to the installation instructions. I would offer a pull request to update the instructions, but they appear to link to a different website (explosionduck.com) so there's no way for me to do that. Perhaps we should pull those into GitHub/ReadtheDocs? I hope future users who want to use Legion will read this issue so they know what to install.

**Comment by synkarius** [comment]
Good idea, moving the instructions into Github/ReadTheDocs. That other site, explosionduck.com is my personal website. I'll link from there to the moved instructions, and update the instructions to include installing the C++ Redistributable Packages tomorrow after work.

**Comment by synkarius** [comment]
New docs page:
https://github.com/synkarius/caster/blob/master/caster/doc/Installation.md

If there are any other nuances, out of date information, etc., please do submit that pull request. :)
