### ISSUE TITLE
Rainbow, Douglas, etc only work on primary monitor

### ISSUE THREAD

**Issue by nathantreid** [synkarius/caster#146]
I have 2 monitors and Rainbow / Douglas only work on my primary monitor. If they could either display on all monitors or display on the current monitor, that would be far more useful in multi-monitor setups.

**Comment by chilimangoes** [comment]
Hi Nathan, you should be able to use the grids on additional monitors by saying "[legion | rainbow | douglass] <monitor_number>". So, for example, "rainbow two" or "legion three". Let me know if that doesn't work.

**Comment by nathantreid** [comment]
Well, that was easy! Thanks!

**Comment by chilimangoes** [comment]
Any time!
