### ISSUE TITLE
Where to put non-english commands?

### ISSUE THREAD

**Issue by seekM** [synkarius/caster#149]
It is possible to use caster with non-english profiles (#148). However, in order to use the current english commands, it seems that they have to be pronounced in a way the recognition enginge for the non-english langauge expects it.

For example, _legion_ can easily be pronounced in a germany way (it's actually the same word). _curse ross ten_ is also doable, but I cannot pronounce _lease_ in a way it would be recognized.

Replacing the commands in e.g. _\_caster.py_ works, but is not ideal since I might want to switch to my english profile for e.g. writing english emails and like to use caster commands then as well. Coping each line which contains an english command and replacing the english word with the one from the other language might be redundant, confusing for multiple langauges and add more complexity due to more rules I think. Therefore, I think it would be good to find a way / place to define commands in multiple langauges and, depending on the langauge loaded, apply the appropiate rules if this is possible.

**Comment by synkarius** [comment]
Some time ago, I introduced a feature called "filter functions". It's a very powerful feature which lets you change any or all of the commands without actually changing the .py files.

However, no one really uses it AFAIK, because it's too complicated. I've given some thought to how I can make it easier to use.

I think I'm going to let the user create a config file that looks like this:

```
"hello" -> "guten tag"
"go up" -> "geh hinauf"
"go down" -> "gehen"
```

That doesn't really capture all of what filter functions can do, but it covers your use case, and probably a lot of other people's use cases too.

I'll try to put that in this weekend.

**Comment by seekM** [comment]
Sounds good!

Will it also be possible to remap the words for the numbers displayed when using legion? I could not find e.g. the command for `14` and was wondering if this is related to [the disabled remapping](https://github.com/synkarius/caster/blob/50113d41ed55cad39ba604949d22e210b8f088a1/caster/lib/dfplus/additions.py#L30-L38)?

**Comment by synkarius** [comment]
This config file upgrade will affect the `spec`s of any rule. So, for this rule:

```
class GridControlRule(MappingRule):

    mapping = {
        "<n> [<action>]":                   R(Function(send_input, nexus=_NEXUS), rdescript="Legion: Action"),
        "refresh":                          R(Function(navigation.mouse_alternates, mode="legion", nexus=_NEXUS), rdescript="Legion: Refresh"),
        "exit | escape | cancel":           R(Function(kill, nexus=_NEXUS), rdescript="Exit Legion"),


        }
    extras = [
              Choice("action", {
                              "kick": 0,
                              "psychic": 1,
                              "light": 2,
                             }
                    ),
              IntegerRefST("n", 0, 1000),
              
             ]
    defaults = {
            "action":-1,
            }
```

... the `spec`s are
"\<n\> [\<action\>]", "refresh", and "exit | escape | cancel".

\<n\> is what controls the numbers you use to select boxes with Legion. Is that what you're talking about, or "kick", "psychic", and "light"?

**Comment by seekM** [comment]
Thank you for explaining this. Yes, I am talking about the `<n>`: Just like saying *guten tag* as a command instead of _hello_, I would like to say _neun_ instead of _nine_ to select the respective box with Legion. Following the definition of `IntegerRefST` leads me to [`IntegerContentST`](https://github.com/synkarius/caster/blob/50113d41ed55cad39ba604949d22e210b8f088a1/caster/lib/dfplus/additions.py#L30-L38) which as I understand it is disabled for the non-english profiles because it caused the crash. Therefore I was worried that I cannot use german words for the numbers to control legion (because the numbers seem to me to not be defined explicitly but by the [builder](https://github.com/synkarius/caster/blob/50113d41ed55cad39ba604949d22e210b8f088a1/caster/lib/dfplus/additions.py#L30-L38) which does not seem to work for the non-english profiles, as stated above). I hope I could make myself clear, please correct me if I understood something wrong!

**Comment by synkarius** [comment]
Wait, so using your German profile, you still have to use English numbers? If so, that's probably Dragonfly's fault,------ but I can broaden the technique I'm using for "Integer Remap" in order to allow remapping of integers to any language (or made up words even).

If I'm understanding you correctly (German profile but English numbers), please open another issue and call it "Generalize Integer Remap". It shouldn't be hard to do, but it's a separate concern.

**Comment by chilimangoes** [comment]
My guess is the root of this English/German numbers issue has to do with that Dragonfly loading error that @seekM reported a few days ago. From the looks of the error message, the solution might be as simple as creating a 'de' language definition with the correct integer names (or telling Dragonfly where to find it off it already exists). Unfortunately I'm not at my computer, and when I get back to my computer I'm pretty swamped with work right now - but I'll poke around the Dragonfly repo on my phone for a bit and see if I can turn up any more clues.

For reference, here were the the two lines from the stack trace that @seekM posted which looked the most relevant:

```
File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\language\loader.py", line 102, in _load_module_for_language
% language)
DragonflyError: Attempt to load unknown language: 'de'
```

And


```
File "C:\NatLink\NatLink\MacroSystem\UserDirectory\caster\lib\dfplus\additions.py", line 5, in <module>
from dragonfly.language.en.number import int_0, int_1_9, int_10_19, int_20_99, \
```

**Comment by chilimangoes** [comment]
OK, so looking at the offending line in [dragonfly/language/loader.py](https://github.com/t4ngo/dragonfly/blob/master/dragonfly/language/loader.py), it's throwing an error if the language code isn't in the `language_map` array defined at the top of the LanguageSpecificLoader class, but that array only has 'en' and 'nl' defined, even though there are directories for other languages, including 'de'.

**Comment by chilimangoes** [comment]
Sorry,  tapped the Close Issue button when I meant to tap on the text box to finish my comment.

So... if I'm reading that file right, getting the German numerals working *might* be as easy as adding a 'de' entry to that array.

**Comment by synkarius** [comment]
For comparison, the relevant section from `natlinkstatus.py`:

```
languages = {"Nederlands": "nld",
             "Fran\xe7ais": "fra",
             "Deutsch": "deu",
             "UK English": "enx",
             "US English": "enx",
             "Australian English": "enx",
             "Indian English": "enx",
             "SEAsian English": "enx",
             "Italiano": "ita",
             "Espa\xf1ol": "esp"}
```

Your idea is definitely worth a shot. I think it's more correct to fix this in Dragonfly than in Caster if that's possible.

**Comment by seekM** [comment]
Adding `"de":  "dragonfly.language.de"` to the map leads to Caster not crashing anymore, even without [the changes](https://github.com/synkarius/caster/commit/9331b8b384cccfe418a67aa419a1ec05e526fb0a) to fix  #148. Therefore, I reverted these changes in the pull request #151.
However, I could not use the german words for calling the numbered boxes because `caster/lib/dfplus/additions.py` by default loads the english numbers. I fixed this in #151 as well. It works now, thank you for your help! What I had to struggle a bit to find out is that the way most of the german numbers > 20 [have to be spoken](https://github.com/t4ngo/dragonfly/blob/94c69ad90f11e21ce2d8d208c85b9ff51ca0eb0e/dragonfly/language/de/number.py#L72) (in the sense of word order) is the same way as the english one: _"multiplier [remainder]"_ - so it is _zwanzig zwei_, although _zweiundzwanzig_ would be the natural way.

**Comment by synkarius** [comment]
@seekM If you have time, would you modify `dragonfly/language/de/number.py` so that the numbers are correct? Then submit a pull request to [my Dragonfly repo](https://github.com/synkarius/dragonfly)? I'd suggest submitting to @t4ngo's repo, but he appears about once per year and then vanishes again. AFAIK, my Dragonfly repo is the most up to date.

**Comment by seekM** [comment]
I will put it onto my todo list. It won't be as simple as changing e.g. `<multiplier> [<remainder>]` to  `[<remainder>]und<multiplier>`, because some numbers are special: E.g. It is _zweiundzwanzig_, but not _einsundzwanzig_ but _einundzwanzig_. Therefore I have to find out how to best define `spec`s for individual numbers.

**Comment by synkarius** [comment]
All of the "fill" tokens like "CLASS" and "PARAMETER" have been replaced by a single fill token, "TOKEN". This simplifies the template-based commands, since a programmer is going to know what to fill them with anyway.

**Comment by synkarius** [comment]
Also, that problem I mentioned about the string comparisons in the navigation commands -- actually it's not a problem and won't affect you.

**Comment by synkarius** [comment]
For people finding this on Google, I simplified Rule Filters (formerly "filter functions") so that @seekM can override English words in specs, extras, and defaults. [New documentation here](https://github.com/synkarius/caster/blob/develop/caster/doc/readthedocs/CCR.MD#rule-filters-simplified).

**Comment by seekM** [comment]
The link for the documentation of simplified Rule Filters above doesn't work anymore. Now it should be [this link](https://caster.readthedocs.io/en/latest/caster/doc/readthedocs/CCR/#rule-filters-simplified).

**Comment by LexiconCode** [comment]
> The link for the documentation of simplified Rule Filters above doesn't work anymore. Now it should be [this link](https://caster.readthedocs.io/en/latest/caster/doc/readthedocs/CCR/#rule-filters-simplified).
Thanks for the heads up, I've edited to reflect the new link!
