### ISSUE TITLE
legion not working

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#15]
All I see is a black square come up in the upper left corner.

**Comment by Versatilus** [comment]
This is on my short list to look at once I'm efficiently awake. It was locking up Dragon, so I need to proceed cautiously.

**Comment by synkarius** [comment]
This also applies to Douglas grid and Rainbow grid.

**Comment by kendonB** [comment]
I was finding that Douglas and Rainbow did work correctly

**Comment by kendonB** [comment]
Looks like Legion is working correctly now. Thanks!
