### ISSUE TITLE
Error during initialisation of Dragon NaturallySpeaking

### ISSUE THREAD

**Issue by findausername** [synkarius/caster#155]
Hello,

I tried to install caster on Windows 8 with Dragon NaturallySpeaking 2012 and Natlink 4.1 papa. Previously I installed the bundle from this website to ensure that I have the right version of Python installed: https://sourceforge.net/projects/natlink/files/
During the initialisation of Dragon NaturallySpeaking there was an unexpected error, so I tried an older version of Natlink which was used in the installation Demo video (Natlink 4.1mike). That also didn't work.

I get the following error message:
 Vocola not active
Error loading _caster from C:\NatLink\NatLink\MacroSystem\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 340, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 9, in <module>
    from caster.lib.ccr.standard import SymbolSpecs
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\ccr\__init__.py", line 3, in <module>
    from core.nav import Navigation
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\ccr\core\nav.py", line 10, in <module>
    from caster.lib.dfplus.additions import IntegerRefST
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\additions.py", line 2, in <module>
    from dragonfly.grammar.elements import RuleWrap, Choice
ImportError: cannot import name RuleWrap
-- skip unchanged wrong grammar file: C:\NatLink\NatLink\MacroSystem\_caster.py
-- skip unchanged wrong grammar file: C:\NatLink\NatLink\MacroSystem\_caster.py
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1mike
  DNS version: 12
  Python version: 27
  Windows Version: 8

Could you please give me a hint to resolve the cause of the error? Thank you

**Comment by synkarius** [comment]
You likely either have the wrong version of Dragonfly installed, or don't have it installed at all. That says you're crashing on a Dragonfly import.

**Comment by JMHow01** [comment]
I also received this error message below, which is very similar. Not sure how to handle this. I've downloaded the most recent dragonfly and I already use it. Any additional suggestions?

Error loading _caster from C:\NatLink\NatLi I also received this error messagenk\MacroSystem\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 309, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 9, in <module>
    from caster.lib.ccr.standard import SymbolSpecs
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\ccr\__init__.py", line 3, in <module>
    from core.nav import Navigation
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\ccr\core\nav.py", line 10, in <module>
    from caster.lib.dfplus.additions import IntegerRefST
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\additions.py", line 2, in <module>
    from dragonfly.grammar.elements import RuleWrap, Choice
ImportError: cannot import name RuleWrap
 
I'm not sure how to handle these errors. Any suggestions?﻿

**Comment by synkarius** [comment]
Dragonfly doesn't use words in its version numbers (like 4.1papa) -- Natlink does. RuleWrap is a Dragonfly class. I suspect that you too did not install Dragonfly correctly. The latest version of Dragonfly is 0.6.6b1. You should follow these instructions (and ignore the annotations, as the problem they were addressing has been corrected): https://www.youtube.com/watch?v=iNAsV4pcnEA

**Comment by synkarius** [comment]
Also, as of Natlink 4.1oscar, you should no longer be putting Caster in the /Macrosystem folder. It will probably still work, but that's not the standard Natlink/Dragonfly configuration anymore. Instead, in the Natlink GUI configurer (start_configurenatlink.py), you should enable and set the `UserDirectory` option.

**Comment by JMHow01** [comment]
Thank you. I watched the video link and reinstalled dragonfly exactly as done in the video and caster appears to be functional now. I don't remember following the videos instructions during my initial install.

**Comment by synkarius** [comment]
Excellent. Glad to hear it.

**Comment by DecisionNumerics** [comment]
However I don't seem to be able to find the words "RuleWrap" anywhere in any of the files in https://github.com/t4ngo/dragonfly.

Perhaps you could tell us which file this portion of code is in?

**Comment by comodoro** [comment]
@DecisionNumerics t4ngo/dragonfly is outdated, Caster uses https://github.com/Danesprite/dragonfly. RuleWrap is in https://github.com/Danesprite/dragonfly/blob/master/dragonfly/grammar/elements_basic.py
