### ISSUE TITLE
Rainbow Grid

### ISSUE THREAD

**Issue by JMHow01** [synkarius/caster#157]
From where do you install rainbow and douglas grid?

**Comment by JMHow01** [comment]
I get this message "Rainbow feature not available without PIL"

**Comment by synkarius** [comment]
Ah. You need to install Pillow. 

http://pillow.readthedocs.io/en/3.2.x/installation.html

**Comment by LexiconCode** [comment]
Closing as the question is answered. May reopen if needed.
