### ISSUE TITLE
Git bash commands not working

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#168]
Everything else in caster seems to be working okay, even in Git bash itself. Are you able to help me with troubleshooting this? Is this something I need to activate?

**Comment by chilimangoes** [comment]
1) Make sure the "gitbash" setting is set to true in `caster/bin/data/settings.json` (I'm pretty sure it's enabled by default, but check just in case).

2) Gitbash is an app-specific grammar, which means that it's enabled/disabled based on what Windows executable has the system focus when you start saying a command. The AppContext is set up at the bottom of the `gitbash.py` and by default is only configured to work when the EXE name matches "sh", which is the terminal app in MINGW and (I think) Cygwin. If you're using something else, like the default CMD in Windows, then it won't work. It's easy to add whatever terminal program(s) you're using by OR-ing additional AppContexts. See the `jetbrains.py` grammar for an example of doing this.

**Comment by kendonB** [comment]
Below is my solution. My bash shell was called "git-bash". Now this seems to work.
```
context = AppContext(executable="sh")
context2 = AppContext(executable="cmd")
context3 = AppContext(executable="git")

grammar = Grammar("MINGW32", context=(context | context2 | context3))
```
