### ISSUE TITLE
how does one put arbitrary text into a command?

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#169]
It would be something like:

``` 
"verbatim <text>": R(Text("<text>"), rdescript=""), 
```
But this produces the error: 

`Exception: Unknown reference name '<text>' in '<text>'`

Question as an aside: would you prefer these types of questions on stackoverflow?

**Comment by synkarius** [comment]
Here or StackOverflow is fine, but Caster doesn't have a SO category.

You need to create a Dictation object in your rule's "extras" section.
Sending from my phone so won't go into detail now but if you need help with
that, please ask and I'll answer when I get home.

**Comment by kendonB** [comment]
I'm not sure how to go about that. The "extras" argument is to the ``R`` function? But I'm not sure how to create a Dictation object.

**Comment by synkarius** [comment]
Glad to help. Have a look at this extra in sample.py: https://github.com/synkarius/caster/blob/master/sample.py#L63

That is what you should do with your own rule. 

If you still have trouble after looking at that, post your entire rule and I'll help you fix it.

**Comment by kendonB** [comment]
Thanks so much for this. I got it to work. The essential elements for future visitors:

```

def type_function(textnv):
    Text(str(textnv)).execute()    
```


```
"type function [<textnv>]":    Function(type_function, extra={'text'})+Key("lparen"),
    }
    extras = [
              Dictation("textnv"),
             ]
    defaults = {"textnv": "", }
```

**Comment by synkarius** [comment]
Or even more simply:

```
    "type function [<t>]":     Text("%(t)s"),
}
extras = [
    Dictation("t"),
]
defaults = {
    "t": "",
}
```
