### ISSUE TITLE
Feature suggestion: dredge with numbers

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#170]
i.e. this will allow the user to go back two tabs.

The requires the alt key to be held down, which doesn't seem to work with the Repeat function.

**Comment by chilimangoes** [comment]
I don't use dredge, but you can use the following commands for switching Windows and tabs:

"(next | prior) tab [<n>]": go <n> tabs forward/backward (n is optional, defaults to 1).

"(next | prior) window [<n>]": go <n> windows forward/backward (n is optional, defaults to 1).

"(next | prior) win [<n>]": same as above, but it's shorter to say.

"switch (win | window | windows)": brings up the window switcher panel (or whatever it's called) and allows you to select the window you want using "Ross/lease/sauce/dunce/tabby" to highlight, followed by "shock" to select the window.

Note: I'm on mobile and not sure if <n> is actually sorted on the "next/prior window" commands. I always prefer to use "switch window" if I'm not switching to the immediate last window. Also note that, without specifying <n>, "prior window" and "next window" will have the same result. So in practice, I only use "prior win" and "switch win".

All of the above are defined in `nav.py`.

**Comment by chilimangoes** [comment]
Hi @kendonB, did the above suggestions work for you or was there another use case that you had in mind and I didn't cover?

**Comment by kendonB** [comment]
Yes, sorry for the lack of feedback! I am quite happily using "switch win" plus directions. It's still not quite as speedy as a dredge with numbers but it's fast enough (probably costing me less than 10 seconds per voice coding day).

**Comment by kendonB** [comment]
Fixed in #521
