### ISSUE TITLE
Feature suggestion: bringme 

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#173]
It would work just like in https://github.com/simianhacker/code-by-voice/blob/master/macros/_bringme.py

I have been using theirs, but their ``open`` function crashes my dragonfly, and the system doesn't seem to be actively developed.

**Comment by LexiconCode** [comment]
Sure @comodoro

**Comment by LexiconCode** [comment]
@kendonB fulfilled by https://github.com/synkarius/caster/pull/273
