### ISSUE TITLE
 Feature suggestion: add "end" and "home" to the standard directions

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#175]
This makes things like selecting lines and getting to the start or end of a document a breeze.

**Comment by kendonB** [comment]
I use "hum" in place of "home" as, for me, it would often mishear "I'm".

**Comment by synkarius** [comment]
`lease`/`ross`/`sauce`/`dunce` all have an optional component, `wally` - when combined with `lease` and `ross`, they act as Home and End. When combined with `sauce` and `dunce`, they act as Ctrl+Home and Ctrl+End respectively.

**Comment by kendonB** [comment]
I see. Yes, that works.
