### ISSUE TITLE
"At sign" doesn't link with other commands 

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#176]
I fixed this in my version by simply changing the command to "atty".

**Comment by synkarius** [comment]
Ah. The spec conflicted with a built-in Dragon command's spec. Your fix would make a good pull request.

**Comment by LexiconCode** [comment]
@kendonB would you be willing to make a pull request with your change?

**Comment by kendonB** [comment]
https://github.com/synkarius/caster/pull/210

**Comment by Versatilus** [comment]
Thanks!
