### ISSUE TITLE
Non Dragon Speak Commands Not Working

### ISSUE THREAD

**Issue by xcasper** [synkarius/caster#184]
Hi, my understanding is that the visual studio commands contained in caster/app/visualstudio.py should start automatically when visual studio 2017 starts. This does not seem to be the case and when I say "enable visual studio" it just tries to print that into the window in visual studio.

I will say I am really new at voice programming but I am not sure what I am missing here.

Upon further investigation im pretty sure it works for anything like f5(resume), break point(f9), but anything like "comment line" or "go to line" where its c-* for the command or ca-* or anything like that seems to not work.

Could this be because I was unable to get Douglas Grid / Rainbow Grid and Legion features working? I have an error saying I need PIL but I have PIL installed in my python27/lib/site-packages folder

**Comment by codingApprentice** [comment]
Hello,
I'm pretty new to voice programming as well, but perhaps
try doublechecking the name of the executable that is running for visual studio in the task manager. I think that the name of the Python file must match back to this name. I have visual studio 2015 whose executable is called devenv.exe so I renamed the visual studio Python file to devenv.py and restarted Dragon NaturallySpeaking. Also, for any commands that don't seem to work, doublecheck that they would work from clicking in the toolbar. I'm new to visual studio, and so some commands didn't seem to work because they weren't even allowed via the toolbar or keyboard shortcuts (but they would be allowed in other specific situations)

And from what I can gather,  it's the files that are in the continuous command recognition (ccr) subfolder that requires a phrase "enable … "

**Comment by xcasper** [comment]
Hey codingApprentice, thanks for that advice. I will give it a shot and update. Can you elaborate on what you mean by "Also, for any commands that don't seem to work, doublecheck that they would work from clicking in the toolbar" Are you talking about Dragon's toolbar or Visual Studio? Also Visual Studio 2017 is also devenv.exe so I will try renaming the file same as you.

**Comment by codingApprentice** [comment]
Visual studio's toolbar.
So for example if you want to do a line comment, go to visual studio's toolbar and make sure that doing a line comment isn't greyed out. If it is greyed out, that would explain why you couldn't do the voice command for it as well, as it relies on doing the keyboard shortcut for it usually.

**Comment by xcasper** [comment]
So it is not grayed out. If I hit ctrl + k, ctrl + c (to do a comment line) or ctrl +k, ctrl + u(to uncomment) it works just fine. The command seems to even be registered by caster because it doesn't type, it just doesn't work. I am actually just getting to try and work on this a bit more now, so I will try renaming the file you suggested.

**Comment by LoganGirard** [comment]
I'm also reproducing this in Visual Studio 2017. none of the commands in the quick reference are working at all. Only dictation. I verified that my commands work in other applications such as Notepad plus plus.

**Comment by xcasper** [comment]
Hi Logan, what windows version are you using? I cannot get even notepad to work. (havent tried notepad++ yet).

**Comment by LoganGirard** [comment]
I am using Windows version 10. creators update I believe. I am using Visual Studio 2017. I managed to get it working but only when I'm not using administrator mode. Which is something I need for my regular development workflow. Dragon NaturallySpeaking will allow me to run it in administrator mode so I'm not sure where that leaves me.

**Comment by LoganGirard** [comment]
I am using Windows version 10. creators update I believe. I am using Visual Studio 2017. I managed to get it working but only when I'm not using administrator mode. Which is something I need for my regular development workflow. Dragon NaturallySpeaking will allow me to run it in administrator mode so I'm not sure where that leaves me.

**Comment by LoganGirard** [comment]
I am using Windows version 10. creators update I believe. I am using Visual Studio 2017. I managed to get it working but only when I'm not using administrator mode. Which is something I need for my regular development workflow. Dragon NaturallySpeaking will allow me to run it in administrator mode so I'm not sure where that leaves me.

**Comment by xcasper** [comment]
I wonder what I am doing wrong. My stuff still tries to recognize commands but then just doesn't do anything. Doesn't type, doesn't do the command, nothing

**Comment by codingApprentice** [comment]
@LoganGirard notepad plus plus also won't allow me to use Caster commands when it's in administrator mode as well. Similarly when setting environment variables which requires administrator mode. But I can use regular Dragon commands, which can be awkward and tedious without the help of Caster formatting and alphabet "press shift c" or "press shift m" et cetera.

**Comment by Versatilus** [comment]
What most of you are experiencing is the result of Dragonfly, and therefore Caster, running in a user mode Python and trying to access windows that are run in administrator mode. Windows doesn't allow this for security reasons. As a "temporary" measure, I have been using my computer in administrator mode for the past two years.

The proper solution for it is to delegate keyboard and window access to a properly elevated program. I was working on this with @chilimangoes , but I get easily distracted by sparkly things and he was caught up by something else. This is a problem that is very much on my radar and I might take another crack at it by the end of the year. What little we got done on it is available at https://github.com/chilimangoes/CasterUIAutomation_POC .

**Comment by chilimangoes** [comment]
@Versatilus is correct. The repo he linked to also has some links to a fairly lengthy conversation on Gitter if anyone is interested in some of the technical details and the various fixes we were discussing. Unfortunately, my personal life is pretty complicated right now and I don't have the time or energy to work seriously on this, but if anyone wants to take point on it, I'll gladly grant them contributor rights to the repository and I can help out a little in a supporting role.

**Comment by LoganGirard** [comment]
can someone explain the hack for this so that I can unblock myself I don't understand what running my computer as administrator mode means I've elevated myself to the administrator doesn't seem to do anything different

**Comment by LexiconCode** [comment]
@Versatilus
I'd be curious in a further explanation as well if you have time.
