### ISSUE TITLE
Sikuli setup error

### ISSUE THREAD

**Issue by codingApprentice** [synkarius/caster#185]
[https://www.youtube.com/watch?v=RFdsD2OgDzk](url)

I am currently trying to follow the tutorial above on how to use Sikuli with Caster.
I first tried to install the latest version of SikuliX, but that didn't produce a separate Sikuli scripts jar file.
So instead, I installed version 1.0.1 located here [https://launchpad.net/sikuli](url)

I set up the settings.json and environment variables as described in the tutorial. However, I get an error (see below). The error doesn't make sense to me as it seems to have an issue with referencing an imported class MergeRule within the _caster.py file only is when I set the variable SIKULI_ENABLED to true in the settings file, but it doesn't have any error messages when it is set to false.

Any possible idea what I'd be going wrong?

___________

Attempting to load CCR anyway...
<type 'exceptions.WindowsError'>
[Error 2] The system cannot find the file specified
<traceback object at 0x10C4F2B0>
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 41, in <module>
    from caster.asynch.sikuli import sikuli

  File "C:\NatLink\NatLink\MacroSystem\caster\asynch\sikuli\sikuli.py", line 100, in <module>
    refresh(_NEXUS)

  File "C:\NatLink\NatLink\MacroSystem\caster\asynch\sikuli\sikuli.py", line 94, in refresh
    launch_server()

  File "C:\NatLink\NatLink\MacroSystem\caster\asynch\sikuli\sikuli.py", line 23, in launch_server
    "-r", settings.SETTINGS["paths"]["SIKULI_SERVER_PATH"]

  File "C:\Python27\Lib\subprocess.py", line 711, in __init__
    errread, errwrite)

  File "C:\Python27\Lib\subprocess.py", line 959, in _execute_child
    startupinfo)

Error loading _caster from C:\NatLink\NatLink\MacroSystem\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 317, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 76, in <module>
    class MainRule(MergeRule):
NameError: name 'MergeRule' is not defined
-- skip unchanged wrong grammar file: C:\NatLink\NatLink\MacroSystem\_caster.py
-- skip unchanged wrong grammar file: C:\NatLink\NatLink\MacroSystem\_caster.py

**Comment by LexiconCode** [comment]
Post the ...\caster\bin\data\settings.json

**Comment by codingApprentice** [comment]
uploaded
[https://github.com/codingApprentice/caster/blob/master/caster/bin/data/settings.json](url)

**Comment by LexiconCode** [comment]
@codingApprentice 
Please test Update Sikuli 1.0.X to Sikulix 1.1.X. #215

**Comment by LexiconCode** [comment]
Thanks for testing! Strangely enough I have a working set up. There are a few issues related to grammar Sikuli commands not being loaded and Sikuli IDE not saving to the correct folder by default.

The original Sikuli 1.0.X worked for most people so there might be something about your setup needs to be ironed out. If you could hop on Gitter and I'll see what I can do to troubleshoot.

**Comment by codingApprentice** [comment]
@LexiconCode 

So I managed to get the server working.
I had to change all references to _jyio in the imports within the io.py file to _io
[jython fix](https://github.com/codingApprentice/Sikulix_Library_112/tree/FixImportIssue)
![sikulix_server_fixed](https://user-images.githubusercontent.com/24398158/38169079-e26a5528-3557-11e8-8393-2044aabb56d0.PNG)

I now also seem to be having the same issues that you referenced in #215 

- Voice commands to launch the server, refresh it, launch the IDE et cetera, don't seem to work.
I can run the IDE manually however, and scripts do seem to work on the Sikuli server. And the default save location seems to be in the right place, i.e. C:\NatLink\NatLink\MacroSystem\caster\asynch\sikuli\scripts 
( which you are having trouble with in #215 ?)

**Comment by LexiconCode** [comment]
what path is Sikuli IDE using when saving the script files?
Incorrect
`C:\NatLink\NatLink\MacroSystem\caster\asynch\sikuli`
Correct
`C:\NatLink\NatLink\MacroSystem\caster\asynch\sikuli\scripts`

**Comment by codingApprentice** [comment]
Here you go
[Sikulix_test - settings.json](https://github.com/codingApprentice/caster/blob/Sikulix_test/caster/bin/data/settings.json)

**Comment by LexiconCode** [comment]
@codingApprentice I would like to close this issue and continue on #215
