### ISSUE TITLE
alphabet doesn't work in words.txt

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#19]
Moved from the other issue.

I also find that replacing alphabet phrases does not work here. e.g.

```
<<<EXTRA>>>
goof -> gas
```
Doesn't seem to work. Is it because the alphabet phrases are extras via a function (`alphanumeric.get_alphabet_choice`)?

**Comment by synkarius** [comment]
This is very likely the same bug as #13. If I can fix #13 and this is still broken, then let's open this one separately.
