### ISSUE TITLE
What does a TokenSet (and auto) do?

### ISSUE THREAD

**Issue by betaorbust** [synkarius/caster#192]
I've noticed that several language rules define TokenSets, which are defined in mergerule.py but nothing seems to use it.
https://github.com/synkarius/caster/blob/ccde4136c07bd9316e24cb0ed77596e28a2ac1f9/caster/lib/dfplus/merge/mergerule.py#L11-L16
It looks to be defined for only CPP, Javascript, Python, and Java at the moment. All the same pattern. Example: https://github.com/synkarius/caster/blob/42a7c9cc64201ea71fc1a66d3e29790106e76701/caster/lib/ccr/javascript/javascript.py#L97-L110

Can you shed some light on how this is being used?

While we're here, can you point me at what is consuming the `auto` property that is set in all the language rules? Example:
https://github.com/synkarius/caster/blob/42a7c9cc64201ea71fc1a66d3e29790106e76701/caster/lib/ccr/cpp/cpp.py#L14-L16

**Comment by synkarius** [comment]
`TokenSet`s are a leftover from an abandoned project. Honestly, I can't even remember what it was supposed to do, but I know it was never finished. 

`auto` was from another abandoned project. That one I do remember. Caster had an option that would attempt to switch to the correct command set automatically by reading the extension of the open file in the title of the active window. So, if this option was active and your IDE window title had ".h" in it, Caster would switch to C++.
