### ISSUE TITLE
For people having issues with the grid system (Legion, Douglas, Rainbow)

### ISSUE THREAD

**Issue by LazoCoder** [synkarius/caster#194]
I was having issues with the Legion, Rainbow and Douglas commands and installing Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 (x86) did not resolve them. The issue was that even though the commands were registering, nothing was happening.

I have two Python versions installed on my computer (Windows 10), Python 2.7 (in C:\Python27) and Python 3.6 (in C:\Python36). The latest version of Python is used by default. I suspect that this is due to the way that my environment variables have been set up during the installation of the newer version. So if I go to command prompt and type ```python -V``` it outputs: ```Python 3.6.2```.

I wanted to see the error for the grid functionality so I navigated into ```C:\Natlink\Natlink\MacroSystem\caster\asynch\mouse``` and I ran the command ```python grids.py``` only to recieve the error ```No module named 'SimpleXMLRPCServer'```. Since this was using the default python instance, it was using Python 3.6. So I tried using Python 2.7 via the command ```C:\Python27\python grids.py -g d``` and it worked. I discovered that Caster was using the default Python (in this my case Python 3.6) instead of Python 2.7.

**TEMPORARY FIX**:
Go into ```C:\Natlink\Natlink\MacroSystem\caster\lib\navigation.py``` and on lines 48, 50 and 52 where it says ```Popen(["pythonw", ...``` and change ```"pythonw"``` to the location of your Python 2.7 instance. In my case: ```Popen(["c:/python27/pythonw", ...```

**PERMANENT FIX**:
Somebody should find the location of the Python interpreter that is running the script and use pythonw from that particular instance (assuming the script is run in Python 2.7). Or find a way to run Python 2.7 in some other way, but in either case, not to assume that a user's environment variables are using Python 2.7 by default.

The final thing that I would like to point out is that I wish the grids would come to the foreground by default because sometimes they don't and so I have to say "kick ... 7 kick" in order to first select it and bring it to the foreground (this is time-consuming) as opposed to just saying "7 kick". But then sometimes it does spawn in the foreground.

**Comment by LazoCoder** [comment]
On another note I would like to thank @synkarius and all the other contributors for creating and maintaining this project. It's made a world of difference for me and has pretty much saved my programming career. God bless you all.

**Comment by LexiconCode** [comment]
Thanks for sharing your experience and work around! It's a pain to manage multiple Python Versions with natlink and dragonfly. You are correct with your suspicion about Default Python utilizing system variables in this case Python 3.6. You may run into more issues if your Python environment variables is pointing to Python 3 natlink, dragonfly and castor require Python 2.7.X. Your feedback is highly appreciated and let us know especially from a productivity standpoint any barriers that you encounter.

**Comment by LazoCoder** [comment]
I've resolved the foreground issue by going into regedit, navigating to  Computer\HKEY_CURRENT_USER\Control Panel\Desktop and changing the value of ForegroundLockTimeout to 0. Now the grid systems always load in the foreground.

Just leaving this here in case anybody else is having the same issue.

**Comment by LexiconCode** [comment]
We should move this into the documentation.

**Comment by LazoCoder** [comment]
Solved in #220

**Comment by kendonB** [comment]
I have made that change to in the registry editor. I still find sometimes that the grids find their way to the background. Shall we reopen?

**Comment by LexiconCode** [comment]
The registry change no longer works within Windows 10.
