### ISSUE TITLE
Proposal: Maintain coding style through yapf.

### ISSUE THREAD

**Issue by Versatilus** [synkarius/caster#197]
I would like to see the project's coding style enforced by feeding all contributions through [yapf](https://github.com/google/yapf). This will enforce a single consistent coding style that is easy to read.

This is my current systemwide yapf configuration:
```
[style]
based_on_style=pep8
column_limit=98
indent_dictionary_value=True
no_spaces_around_selected_binary_operators=set(["*,/"])
```

+ PEP8 is a great place to start.
+ This column limit relaxes the restricting feeling of a 79 column line length, but still allows me to open two files side-by-side in my favorite editor.
+ Indenting dictionary values makes them easier for me to read.
+ I just happen to like the way that operator grouping looks.

I'm open to all kinds of feedback, especially different options to include. There are quite a few options I haven't played around with yet. This just seemed like a solid basis to get me started.
 
Unless @synkarius says otherwise, this is how all of my future contributions will be formatted.

**Comment by LexiconCode** [comment]
Documentation for Yapf support by editor. #209
