### ISSUE TITLE
Improvement for different Words with identical pronunciation

### ISSUE THREAD

**Issue by gerrish** [synkarius/caster#200]
Suppose I am trying to dictate the word write but Dragon insists on returning the word right. Apologies if there is a better way to do this, but here is a rough idea I implemented locally to fix this:
A new format command which returns the n first(default 1) Words from dictation.
So you can say write book and the extra context increases accuracy but you don't have to edit out the useless dictation.
 
Just in case this is a good idea, I would like to implement it.

**Comment by LexiconCode** [comment]
Give it a shot implementing it and we will take a look.

**Comment by LexiconCode** [comment]
Have you made any progress?

**Comment by gerrish** [comment]
The partial format command does this!

**Comment by LexiconCode** [comment]
Consider this are closed unless we need to reopen.
