### ISSUE TITLE
Application grammars should take precedence over global grammars with identical command phrases

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#202]
This could be dragonfly related more than Caster. 

The primary reason for an an identical command phrase in an application grammar that exists in global grammar is to override the global grammar implementation. This should include both dragonfly and Dragon NaturallySpeaking.

For instance the `select all` as a global command most windows applications use `control + a`.
if the application is a different shortcut or implementation the global command takes supersedes the local application command.

```
 "select all": R(Key("c-a"), rdescript="Global: Select 
 "select all": R(Key("c-o"), rdescript="An Application: Select
``` 

Current implementation
`global grammar "select all": Key("c-a") overrides "select all": Key("c-o") local grammar`
Proposed change
`"select all": Key("c-o") should override "select all": Key("c-a")`

**Comment by Versatilus** [comment]
Caster seems to do this for its own custom commands, but certain global commands can be a different beast altogether. Sometimes it works and sometimes it doesn't and I don't know why. I'm guessing making it consistent would require manually disabling Dragon's built-in command. It's definitely worth looking into, but I'm not terribly optimistic.

**Comment by Versatilus** [comment]
It's probably best practice to simply avoid phrases that are already used by Dragon, even if they make the most sense in the context.

**Comment by LexiconCode** [comment]
Most likely so unfortunately. At least it's a known issue and should be documented as such when we have time.
