### ISSUE TITLE
Free Dictation intermittently not recognized within applications?

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#221]
This is most likely a bug within Dragon NaturallySpeaking itself but I want to understand if other people are experiencing it. 

The description of the problem can be described as freely dictating within an application all the sudden Dragon NaturallySpeaking doesn't recognize free dictation. However it does recognize global commands within the same application. 

So if you have application `A and B`

When dictating in application `A`  DNS suddenly stops recognizing dictation `"please say that again"`
Bringing `B` application in the foreground and dictate everything works as expected. If you quickly switch back to Application `A` Free dictation is still unrecognized. In the event that you stay in application  `B` long enough a number of minutes and switch back to `A` the issue may resolve itself. If you try to wait it out an application `A` may or may not resolve.

**Comment by chilimangoes** [comment]
I don't think I've experienced this. What version of DNS are you using?

**Comment by LexiconCode** [comment]
I have experiences with DNS 13, 14 and 15. The frequency seems to become much more pronounced In 14 and 15.

**Comment by Versatilus** [comment]
I've never experienced this myself. Does this happen with different programs?

**Comment by chilimangoes** [comment]
That would my next question. If it happens with a specific program or programs. I actually don't use free dictation in many programs. When I need to do dictation rather than code, I tend to mostly dictate into notepad and then copy/paste.

Actually, now that I think about it... I have had problems with dictation stopping working in Outlook 365. But I have so many other problems with Outlook that I figured it was Outlook's fault.

**Comment by LexiconCode** [comment]
It can happen with any program even those that aren't supported by dragonfly or caster. That makes me think it's a bug related to DNS.

**Comment by LexiconCode** [comment]
[A video demonstrating the issue](https://ufile.io/l5q8e) to download.
There are two workarounds restarting the application or restarting DNS.
