### ISSUE TITLE
Transformers don't work on MergeRules

### ISSUE THREAD

**Issue by synkarius** [synkarius/Caster#23]
MappingRules seem unaffected. GIven that MergeRules don't do anything fancy anymore, this probably has to do with the merge process.

**Comment by synkarius** [comment]
This seemingly does not have to do with RepeatRule or `_create_repeat_rule`. I commented out that whole function and returned just the input MergeRule. As expected, CCR was disabled. However, it didn't make my transformer modifications work.

**Comment by kendonB** [comment]
@synkarius FYI, I can confirm that your ModestTransformer example works. Great!
