### ISSUE TITLE
Allow for adding to or modifying commands from the /user directory

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#232]
I have made myriad changes to commands throughout caster as Dragon had trouble understanding the way I say some default words in my accent. Now, I have code which differs substantially from the core codebase making incorporating new changes difficult. 

A solution to this problem could be to allow users to somehow remap commands in /user.

This would also potentially allow caster developers to scrape the /user files from users on github to see what commands might be problematic.

**Comment by gerrish** [comment]
Read about rules this is already possible. For a tl;dr see the examples in user/rules.

**Comment by LexiconCode** [comment]
[Rule Filters](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/examples/rules/Caster%20Rules/).

**Comment by kendonB** [comment]
Thanks heaps
