### ISSUE TITLE
Alias Commands are nonfunctional

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#244]
The command `alias <something>`seems to be broken. Supposedly you can create commands on-the-fly by highlighting text on the screen and say  `alias <something>`. [Alias Documentation](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/Alias/)

Nothing was added to `aliases.json` after attempting to  `alias <something>`.

**Comment by gerrish** [comment]
Do you get any errors from natlink?

**Comment by LexiconCode** [comment]
Excellent! For reference  https://github.com/synkarius/caster/pull/245

**Comment by gerrish** [comment]
Thank you I will do so in the future
