### ISSUE TITLE
Comments in rule filter files

### ISSUE THREAD

**Issue by Danesprite** [synkarius/caster#265]
Hello all. I noticed that both line and in-line comments are supported in filter files, but the docs don't mention it at the moment. Perhaps the [Rule Filters](https://caster.readthedocs.io/en/latest/caster/doc/readthedocs/CCR/#rule-filters) section could be changed to mention that?

**Comment by LexiconCode** [comment]
We should definitely update the docs.

**Comment by LexiconCode** [comment]
@Danesprite Let me know what you think and I'll close the issue.

**Comment by Danesprite** [comment]
Looks good. Yeah, I'll let you know if I notice anything else.
