### ISSUE TITLE
File dialogue not working?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#27]
To reproduce:

1. Say "enable file dialogue"
2. Open a save dialog
3. Say "navigation pane"

It should move focus to the left pane but it does not. I don't think the context is currently going through like it did before.

**Comment by synkarius** [comment]
Is this possibly the same bug as #25?

**Comment by kendonB** [comment]
No I still had this problem after multiple boots.

**Comment by kendonB** [comment]
On my phone so can't fix this right now but this is due to missing quotes in the title context list
