### ISSUE TITLE
The 'record from history' command does not execute.

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#272]
'record from history' is a command that uses self modifying rule.

**Comment by mrob95** [comment]
I have this also.

**Comment by comodoro** [comment]
Chain alias seems not to work for me. Vanilla alias is actually being instatiated twice - once in _caster.py, once in alias.py. Does `CCRMerger.add_selfmodrule` work?

**Comment by LexiconCode** [comment]
@comodoro Even though the underlying cause may be related to the selfmodrule I've opened up a separate issue for the 'chain alias' command #279. 

Some excellent points to investigate comodoro.

**Comment by comodoro** [comment]
Do I have the workflow wrong? Self modifying rules have to be enabled apparently, just like global rules. But then the `feature_rules` Section in settings seems to be redundant as it is not related to CCR merger handling of adding self modifying rules

**Comment by LexiconCode** [comment]
@comodoro say 'complete' it looks like we need to add that to the documentation.

I still consider this a bug because it should not have to be activated in ccr.json and settings.json.

**Comment by mrob95** [comment]
Activating the recording functions in the json files did not fix this for me. I checked the RecognitionHistory() dragonfly function and it was just returning empty lists. **Updating to dragonfly2 solved the problem.**

**Comment by LexiconCode** [comment]
@mrob95 another piece to the puzzle. Now that you have it functioning could you disable/enable in each ccr.toml and settings.toml one at a time and see what the results are as well? I believe both are required to work.

**Comment by LexiconCode** [comment]
Resolved by Converts ccr.toml [selfmod] as true instead of false. #306
