### ISSUE TITLE
Replace .docx with LaTeX for Caster_quick_reference

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#288]
[LaTeX](https://www.latex-project.org/)  it includes features designed for the production of technical and scientific documentation. 

**Advantages**
- Its human readable format which will allow us to take full advantage with Git.
- Convertible to PDF
- Powerful formatting capabilities which should be able to replicate `Caster_quick_reference.docx` formatting.
- Open source format with many editors or online editors for LaTeX.
 
**Disadvantages**
- LaTeX is not as ubiquitous format as .docx.

**Comment by mrob95** [comment]
I was thinking this too. I'd be happy to put something together unless you have already started working on it?

**Comment by LexiconCode** [comment]
@mrob95 I have not started working on it. Feel free to pursue it.

**Comment by LexiconCode** [comment]
Fulfilled by 'Migrate Quick Reference to LaTeX #299'
