### ISSUE TITLE
dragonfly Key and Mouse classes used instead of castervoice.lib.action classes

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#30]
Was this deliberate? e.g. in nav.py we need to use:

`from castervoice.lib.actions import Key, Mouse`

rather than

`from dragonfly import Key, Mouse`

to get Aenea to work correctly.

**Comment by synkarius** [comment]
No. It was not deliberate. I deliberately got rid of the `imports` module because asterisk imports impede clarity and because I figured it would probably make deep reloading easier later, but I did not intend to revert all of those back to the Dragonfly versions.

**Comment by kendonB** [comment]
I believe this issue is now fully resolved with the exception of 1 in `r.py` that #34 sneaks in.
