### ISSUE TITLE
Duplicate choice in nav.py

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#318]
Looks like there's a duplicate of `"gum": 1,`  choices for spacing in nav.py
https://github.com/synkarius/caster/blob/55b70e409d29bd5558eb1a1e64689b69ac7a7a38/caster/lib/ccr/core/nav.py#L261

**Comment by mrob95** [comment]
One is "gum" and the other is "gun". I'm not sure of the reason for it, maybe to improve recognition accuracy?

**Comment by LexiconCode** [comment]
Ah thank you I misinterpreted it
