### ISSUE TITLE
Rules getting rejected

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#32]
```
SpellingWindowRule rejected due to rule/details combination errors: MergeRules must have a ccrtype
WindowsSpeechRecognitionRule rejected due to rule/details combination errors: MergeRules must have a ccrtype
Alias rejected due to rule/details combination errors: MergeRules must have a ccrtype
SublimeRule rejected due to rule/details combination errors: MergeRules must have a ccrtype
OutlookRule rejected due to rule/details combination errors: MergeRules must have a ccrtype
DragonRule rejected due to rule/details combination errors: MergeRules must have a ccrtype
```
This one seems easy - I will have a go at fixing it

**Comment by kendonB** [comment]
After the obvious fix of adding ccr types to these rules I get this:

```
SpellingWindowRule rejected due to detail validation errors: ccr types must not have 'name'
WindowsSpeechRecognitionRule rejected due to detail validation errors: ccr types must not have 'name'
Alias rejected due to detail validation errors: ccr types must not have 'name'
SublimeRule rejected due to detail validation errors: ccr types must not have 'name'
OutlookRule rejected due to detail validation errors: ccr types must not have 'name'
DragonRule rejected due to detail validation errors: ccr types must not have 'name'
```

**Comment by LexiconCode** [comment]
I don't think the validator "MergeRules must have a ccrtype" is catching all the rules with missing ccrtype on first boot (Config files generated). first food the validator checks only DragonRule. "MergeRules must have a ccrtype". The 2nd boot the validator seems to check all grammars as seen in the error message from kendonB.

**Comment by synkarius** [comment]
The first boot thing is interesting. Can we link to this in #25 since it's first boot related?

**Comment by synkarius** [comment]
@LexiconCode The validators were fine, but only the core rules were being loaded on first boot, which is incorrect per our conversation about discoverability.

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode The validators were fine, but only the core rules were being loaded on first boot, which is incorrect per our conversation about discoverability.

The issue makes total sense now with the core rules only being loaded.

**Comment by synkarius** [comment]
Eh, it's a new system. No need to be embarrassed.
