### ISSUE TITLE
Always-on window polling for command mode

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#33]
As per @chajadan's suggestion, add always-on window polling to monitor when command mode should turn on and off.

- trigger via keypress
- make enable-able in the settings

**Comment by synkarius** [comment]
Make the key for the keypress configurable and settings: "ASCII"

**Comment by chajadan** [comment]
it occurs to me -- you could send a sequence of keys such as "Lshift, Rshift, Rshift, Lshift": such keys won't need to be gobbled up, since they won't alter the window with foculs, so as long as you poll the keyboard and restore any keystates in action (such as shift down), it would be an incognito sequence you could catch and not likely to be a false positive.

**Comment by synkarius** [comment]
That's a great idea about using the shift key. I have basically got this working now except for one thing. After about 8-11 keypresses, pyHook seems to stop detecting anything, whether i send it via win32 or just by pressing keys on the keyboard. Then, I have to reboot Dragon NaturallySpeaking to make it detect the next 8-11 times. Do you have any idea why that might be?

**Comment by synkarius** [comment]
Disregard that. It's not 8-11 keypresses, it's 8-11 keypresses which trigger the Mimic action.

**Comment by chajadan** [comment]
I don't quite follow -- I can't tell if you figured it out yourself, or not. If not, if you can link me to the code it would help. I've never had the hook stop registering, but my hooks only stay on for short periods until they've gathered what they are expecting, and then they shut down until I purposely initiate them by a voice command.

**Comment by synkarius** [comment]
I haven't figured it out yet. Here are the relevant sections of code.

This is the script which runs externally. If it detects that a window has changed at all, it presses whenever key the settings file tells it to, in this case, RShift. It works fine, no problems.
https://github.com/synkarius/caster/blob/master/asynch/auto_com/poller.py

This is the one which is run from inside Dragonfly. If it gets inside the if statement on line 35, it will execute those Mimic commands when they are supposed to be executed (when the designated keypress is detected) for the first 8-11 times, then after that, the OnKeyboardEvent callback doesn't execute anymore, nor does it throw any errors. It just fails silently.
https://github.com/synkarius/caster/blob/master/asynch/auto_com/hooks.py#L35

Also, let me say, whether I figure this out or not, thank you for the suggestion and the help. :-)

**Comment by chajadan** [comment]
This first thing to do that may address it is: your hooks need to return True or False. False to eat up the key and not pass it along (it won't even type out), or True to acknowledge and pass it along. In your case I expect True -- which is why I recommend a sequence of non-printing keys. When you don't return True or False, you easily end up in non-functional situations (I learned the hard way -- but it was very clearly not working from the beginning and that was why for me).

**Comment by chajadan** [comment]
You mentioned that it silently fails, but lack of executing wouldn't qualify in my head as a failure on its part. And I'm happy to help! I'm all about dragonfly coding lately =)

**Comment by synkarius** [comment]
I'm doing the hooks wrong? I thought I was returning true on line 45.
https://github.com/synkarius/caster/blob/master/asynch/auto_com/hooks.py#L45

**Comment by chajadan** [comment]
I tried to delete that message -- an incorrect observation on my part.

**Comment by synkarius** [comment]
Ah, sorry, I have just left this tab open in my browser, so your update didn't show. I refreshed, so now the message is gone.

**Comment by synkarius** [comment]
No, after the failure point, OnKeyboardEvent doesn't get called at all.

**Comment by chajadan** [comment]
You seem to use a global pyHook manager -- maybe that's the issue -- you
use hooks elsewhere?

I have multiple managers that are at module level, and they don't conflict.
pyHook seems to only allow a single hook per event type.

You can put debug code in the pyHook code under SubscribeKeyDown to see if
something else is getting set. Or just print out the pyHookManager's
keyboard_funcs dictionary to make sure your callback is still registered at
the point of failure.

**Comment by synkarius** [comment]
I'm pretty sure the hooks weren't being used elsewhere, but you gave me an interesting idea which seems to have solved my problem.
>my hooks only stay on for short periods

I tried reregistering the hooks every single time a Mimic action is executed, and now they don't shut off. It's not pretty but it works. Thanks again!
