### ISSUE TITLE
Is it possible to replace phrases using words.txt?

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#341]
I'd like to, for example, replace "fly lease" with "laib". Is this possible in words.txt?

If not, is it possible to use words.txt to generate shorthands that "Mimic" phrases? i.e. "fly lease" would still exist but I could also use "laib".

**Comment by LexiconCode** [comment]
Not to my knowledge. 'fly' and 'lease' are two different specs. words.txt only works for single string spec replacement globally. 

That means if you have two specs with the word 'orange'
```Python
"color orange":
            R(Text("favorite color"), rdescript="Colors"),
"orange fruit :":
            R(Text("a delicious fruit"), rdescript="Fruits"),
```

Now if you change `orange` to `red` using simplified filter rules.
`orange -> red` via `words.txt`

```Python
"color red":
            R(Text("favorite color"), rdescript="Colors"),
"red fruit :":
            R(Text("a delicious fruit"), rdescript="Fruits"),
```

Your best alternative is to create a new spec. 
```Python
       'laib':
            R(Playback([(["fly", "lease"], 0.0)]), rdescript="My spec: fly lease command"),
```

It would make an interesting feature request to have something similar for mimicking via `Playback`
spec, spec -> 'compound' spec
`fly,lease -> laib`

**Comment by LexiconCode** [comment]
I've discovered that you can actually replace entire specs using `words.txt`.

- if there's any extras in the spec those definitions need to be the same to match the original spec. However for the moment for some reason simplify transformers ignore specs extras with \<text> may be a bug or by design more research is needed.
```
<<<ANY>>>
(lock Dragon | deactivate)  -> (sleep dragon | turn off) 
(lock Dragon | deactivate)  ->  turn off
lock Dragon  -> (sleep dragon | turn off)  
```
