### ISSUE TITLE
AppContext drops off when in save/open dialog boxes in RStudio

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#349]
This "used to work". I now find that caster no longer seems to think I'm in RStudio when the open/save dialog boxes are active. Any advice for troubleshooting what AppContext *is* on when the dialog boxes are active would be helpful. And do you expect the RStudio context to still be on when the dialog box is open?

**Comment by comodoro** [comment]
I see there is window title matching in rstudio.py:

`context = AppContext(executable="rstudio", title="RStudio")`

So in dialog boxes it might not work. Solution would be to remove the title parameter. Might be considered a bug.
