### ISSUE TITLE
Rdescript are not being generated for MappingRule actions that don't have them.

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#38]
The issue is not a bug per say: All MappingRule actions return `None` to the Natlink window.

This is the second reason (which I forgot) that MergeRules were used for MappingRule :/

To be clear the following code functions as expected in the following for MergeRules.
https://github.com/synkarius/Caster/blob/d9a33f3716cead97b2016752aa97cc995ab4906a/castervoice/lib/merge/mergerule.py#L59

The question comes down to what to we do about this inconsistent user experience? 

1. We could switch MergeRules to MergeRules. See https://github.com/dictation-toolbox/Caster/issues/672#issuecomment-521336616

2. Eliminate the feature altogether utilize Dragonfly RPC methods for speech state & recognition history. The quarks of threading with back ends like Nalink are thankfully managed by Dragonflys RPC  implementation. Reference [1](https://github.com/dictation-toolbox/dragonfly/pull/90) and [Documentation](https://dragonfly2.readthedocs.io/en/latest/rpc.html)
3. Other thoughts are welcome.

I recognize this may be out of scope but it's a good place to bring it up for discussion.

**Comment by synkarius** [comment]
I'd be in favor of 2.

**Comment by synkarius** [comment]
Making everything a MergeRule 
1. would just exacerbate grammar complexity issues, and
2. isn't even necessarily good for the user even if there were no complexity limits.

Let's imagine that there were no complexity limits at all. You would still want some commands to be unchainable with other commands. Figuring out which commands those are and why is part of good rule design I think.

**Comment by LexiconCode** [comment]
I agree MergeRule this definitely undesirable. A quote from earlier to clarify the issue further.

> However reimplementing AsynchronousAction then dropping Context Stack sounds like it would clean up the CodeBase. Losing rdescript would be difficult without its functionality replaced. Simply because some commands aren't self-explanatory. All in all `stack.py` should go to the chopping block.

Command history is informative but having Doc like the registered commands is serves another purposee. Fundamentally recognition history informs the user on what command been dictated verbatim without clarifying the functionality of that command. This role is what R function has been in the CodeBase.

**Comment by synkarius** [comment]
Here's my suggestion then: create a transformer which fills in the missing rdescripts. That's a good step towards getting rid of stack.py too.

**Comment by kendonB** [comment]
I agree with having a transformer (not in the user folder) to add the spec as the rdescript for those that are missing.

**Comment by kendonB** [comment]
We would also want the transformer to run last so that user commands via user transformers get transformed by this one.

**Comment by LexiconCode** [comment]
Those are some really good points.

As a side note theoretically could words.txt functionality be made into its own independent transformer if order can be guaranteed internally. Whereas in the user transformer folder orders not guaranteed.

**Comment by synkarius** [comment]
Hmm. So, given the decision about transformers, this one needs some rethinking. Looking at `stackitems.py`, I wonder if we can't just generate the message there instead of needing `rdescript`.

**Comment by LexiconCode** [comment]
> 
> 
> Hmm. So, given the decision about transformers, this one needs some rethinking. Looking at `stackitems.py`, I wonder if we can't just generate the message there instead of needing `rdescript`.

I'm not sure how you're going to untangle `stackitems.py` from `stack.py`.

**Comment by synkarius** [comment]
>I'm not sure how you're going to untangle `stackitems.py` from `stack.py`.

I don't think I understand this comment. The two do not need to be disentangled for my suggestion to work. It's just a matter of having all the necessary information available in `stackitems.py`, which as you correctly point out, probably involves `stack.py`.

**Comment by LexiconCode** [comment]
There should be buttons transfer the issue on the right of the screen

![image](https://user-images.githubusercontent.com/24551569/68061942-5a9d4280-fcd5-11e9-9453-7257fa7e8e85.png)

**Comment by LexiconCode** [comment]
resolved in https://github.com/dictation-toolbox/Caster/pull/709
Although it does needed move out of the grammar manager in a future date.
