### ISSUE TITLE
Companion config do not seem to enable/disable rules as expected

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#39]
```companion_config.toml
VSCodeCcrRule = ["VSCodeNonCcrRule"]
```

This can be seen by saying enable `Visual Studio Code Non Continuous`

One would expect a few things to happen
- saying enable `visual studio code continuous` the VSCodeCcrRule both should be enabled simultaneously
-  That if either VSCodeCcrRule or VSCodeNonCcrRule disabled they both would become disabled simultaneously

Currently it seems unable to disable VSCodeNonCcrRule once enabled say `disable Visual Studio Code Non Continuous`

I have to experiment with other companion rules.

**Comment by synkarius** [comment]
This is actually the "correct" behavior unless old Caster did otherwise. I'm not saying it's how it should be, just that in terms of old/new feature parity, I don't think this is a rewrite-related "bug". I would test old Caster's behavior, but I am traveling this entire weekend and my laptop is not Windows.

**Comment by LexiconCode** [comment]
With my expectations sure but being unable to disable a rule once activated could be related?

**Comment by synkarius** [comment]
Sorry, I misread what you said before. What I meant to say is that the "correct" behavior is:

- enabling a rule with a companion enables them both
- disabling the rule which enabled the companion disables the companion
- disabling the companion does NOT disable the rule

I thought you were asking for the third thing there. It seems now that you're saying that you just can't shut off the companion, period, after enabling via the rule.

**Comment by LexiconCode** [comment]
Strange I'm not able to reproduce this now
