### ISSUE TITLE
better window switching

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#4]
I really have no idea how to do this. Suggestions are welcome.

**Comment by synkarius** [comment]
Also, tab switching in IDEs

**Comment by synkarius** [comment]
This is the "list all Windows" command in Dragon. No need to reinvent the wheel.

**Comment by synkarius** [comment]
This will be great with the command window

**Comment by synkarius** [comment]
The Window monkey patch will help with this as well.

**Comment by synkarius** [comment]
Window monkey patch doesn't work:
* fuzzy string matching for title and exe, use 
* rename "monkeypatch.py" to something else, as we're not actually monkeypatching anymore

**Comment by Zone22** [comment]
If you get a moment could you clarify what you mean by better Windows management?

is this something that might be used?
https://cygwin.com/index.html

**Comment by synkarius** [comment]
That Microsoft reference is good to have around, but actual window management is well beyond the scope of what I intend to do with this one. I should have said "window switching". I've changed the title to reflect this. This is just going to be a simple command that lets me switch windows by saying the name of the executable or the window title.
