### ISSUE TITLE
MappingRules grammars do not update after a 2nd reload

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#40]
The following is a test case user rule. According to my tests MappingRules after the second reload do not update after reload. The issue only occurs per grammar. 

- Generic Workflow
1. Start up caster
2. Make a change to file
3. Save file
4. Wait till the file is reloaded seen in the natlink window
5. Test dictation output (same or different as previous change)
6. Repeat steps above as necessary (Reloading twice with a new change each time to reproduce the issue)

Detailed steps to reproduce
**Note**: My test phrase `get hello` produces `hello` 

When Castor first loads everything works as expected with the following.
   `"get <location>":  Text("%(location)s"),`
test phrase `get hello` produces `hello` as expected.

First change and it reloads as expected.
   `"get <location>":  Text("dd %(location)s"),`
test phrase `get hello` produces `dd hello` as expected

Second change and it reloads but does not update.
   `"get <location>":  Text("dfesf %(location)s"),`
 
Test phrase `get hello` produces `dd hello`    which is not expected. The results should be `dfesf hello` .
Only after a reboot caster at this point `get hello` produces `dfesf hello` as expected.

**Test case grammar**
```Python
from dragonfly import Key, Dictation, MappingRule, Text, Function, Choice

from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.additions import IntegerRefST
from castervoice.lib.merge.state.short import R


class master(MappingRule):
    mapping = { 
        "get <location>":  Text("%(location)s"),
    }

    extras = [
    Dictation("location"),
  ]

def get_rule():
    return master, RuleDetails(name="master")
```

Further testing with Keys, Functions or other dragonfly elements maybe beneficial. 

**Update**
Replicated with `Functions` with updating print statements
```Python
def test():
  print "success" 
```
Replicated with updating `Key`s
`"test":  Key("c-a"),`

**Comment by kendonB** [comment]
I can confirm this one for `MappingRule`s but not for `MergeRule`s. This doesn't seem to be exclusive to usee rules either. I have tested for both a user rule and a caster rule.

**Comment by kendonB** [comment]
I retested this on `rstudio.py` (not a user file) and even the first reload doesn't seem to work.

**Comment by synkarius** [comment]
I definitely tested this and saw it work, but that must have just been on a MergeRule. Makes sense.

**Comment by synkarius** [comment]
Thank you much, gentlemen, for the test procedure, confirmation, and analysis. Couldn't ask for a better bug. :)

This should be good to go.
