### ISSUE TITLE
Error with APP ccr rules when two are enabled

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#42]
My user rule is:

```python
from castervoice.lib.const import CCRType
from castervoice.lib.actions import Key
from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.state.short import R
from castervoice.lib.merge.mergerule import MergeRule

class RStudioUserCCRRule(MergeRule):
    pronunciation = "are studio user continuous"
    mapping = {
        "find rstudio":
            R(Key("c-f"), rdescript="RStudio: Find"),
    }
    extras = []
    defaults = {}

def get_rule():
    details = RuleDetails(executable="rstudio",
                          title="RStudio",
                          ccrtype=CCRType.APP)
    return RStudioUserCCRRule, details
```
I'm not 100% sure this is a bug or if it's a mistake I made. The error:
```
Error loading _caster from C:\Users\kmbel\Documents\caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\kmbel\Documents\caster\_caster.py", line 33, in <module>
    control.init_nexus(_content_loader)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\control.py", line 7, in init_nexus
    _NEXUS = Nexus(content_loader)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\nexus.py", line 83, in __init__
    self._grammar_manager.initialize()
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 91, in initialize
    self._remerge_ccr_rules()
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 192, in _remerge_ccr_rules
    ccr_rules_and_contexts = self._merger.merge(active_ccr_mrs)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\merge\ccrmerging2\ccrmerger2.py", line 60, in merge
    contexts = CCRMerger2._create_contexts(app_crs, rcns_to_details)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\merge\ccrmerging2\ccrmerger2.py", line 131, in _create_contexts
    negation_context += ~context
TypeError: unsupported operand type(s) for +=: 'LogicNotContext' and 'LogicNotContext'
```

**Comment by kendonB** [comment]
Okay I figured out how to reproduce this without user code.

1. Wipe out the user folder
2. Reboot dragon
3. Say "enable eclipse jump"
4. Say "enable visual studio code continuous"

It should produce a similar error to above. So it looks like only one APP ccr rule is able to be active at once or the system breaks.

**Comment by LexiconCode** [comment]
Replicated on my machine as well

**Comment by synkarius** [comment]
I'm not sure if this is a Python operator error or if you just can't combine Dragonfly LogicNotContexts, but it's one of those. If it's the latter, there may not be much I can do about it unless @DaneSprite wants to get involved.

Here's the idea. You have three CCR rules: nav, app1, and app2. nav is global. You want to be able to use it by itself, but also with app1 and app2. So your three repeat rules look like this:

nav (not in app1 or app2, but anywhere else)
nav + app1 (app1 context only)
nav + app2 (app2 context only)

It's that first one I'm trying to combine LogicNotContexts for. I may be wrong about this, but I do not believe that this actually works in old Caster. So I'm happy to just shut it down in new Caster if need be and just interpret app CCR grammars as global CCR grammars, as I believe happens in old Caster IIRC. But I'll have a look at it. It might just be that I can't use the += operator or something simple like that.

**Comment by Danesprite** [comment]
Hi @synkarius. You want to use the `&=` operator instead to get the "global" nav rule working like you described.

BTW, sorry I haven't gotten around to testing the rework yet. I don't keep up with Caster issues much, so feel free to mention me again if you run into other Dragonfly-related issues :-)

**Comment by synkarius** [comment]
@Danesprite Ah! Perfect, thank you. This should be very easy to fix then.

No worries about the testing. I'm pretty short on time too these days, completely understand.

**Comment by synkarius** [comment]
@kendonB @LexiconCode This one should be good to go.

**Comment by Danesprite** [comment]
@synkarius No problem :-)
