### ISSUE TITLE
Text formatting defaults

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#44]
After using a text formatting command, the next time, the text formatting parts can be omitted and the text will be formatted in the style that it was the previous time. Additionally, the current style is displayed in the status window.

**Comment by Zone22** [comment]
How do you dictate text using caster?

**Comment by synkarius** [comment]
Use the commands from section [(5)] (https://github.com/synkarius/caster/blob/master/CasterQuickReference0.4.7.pdf) of the Quick Reference guide. If you combine them, capitalization comes first, then spacing. 

Example:

    "tie gum bow red hat"   ---> RedHat
    "laws bow red hat"      ---> red hat
