### ISSUE TITLE
<launch> to bring me as <key> not working

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#45]
To reproduce:

Say "enable bring me"
Say "bring me caster user"
Select the rules folder
Say "folder to bring me as 1 2 3 4"

I get this error:
```
ERROR:action:Exception from function _bring_add:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
TypeError: _bring_add() takes exactly 3 arguments (2 given)
ERROR:action.exec:Execution failed: Function(_bring_add): _bring_add() takes exactly 3 arguments (2 given)
```

**Comment by kendonB** [comment]
I don't think that `self` gets passed through but I haven't been able to figure out how to get it to pass through.

**Comment by synkarius** [comment]
I'll leave it to you to close this one since you were the reporter, @kendonB.
