### ISSUE TITLE
Notes: Theoretical Problems

### ISSUE THREAD

**Issue by synkarius** [synkarius/Caster#46]
While fixing #16, I ran across a couple of strange situations which could in theory arise. I am going to resolve them in the simplest way: by implementing the solution closest to old Caster's behavior. But I want to make a note of them here because (1) I think they're interesting, and (2) they might come up at some point.

Alright, first point: in old Caster, app CCR rules could knock each other out. By accident, I implemented the ClassicMergeStrategy class in such a way that now they can't.

The first thing I want to note is that this is incorrect so long as contexts can be overlapping. In other words, if you have two rules and one has a context which covers X and Z and another one has a context which covers X and Y, their contexts are overlapping. I do not think we want to forbid overlapping contexts because that imposes a seemingly rigid design constraint in order to prevent something which is probably very unlikely to actually occur. App CCR rules should be able to knock each other out if they're overlapping at all. However, this adds a lot of complication to the KO logic and it's already complicated enough (mostly due to app CCR rules and the n+1 rules thing documented in the merger somewhere). The way which is easier to think about KO for both users and rule makers is just plain and simple spec overlap. Once you introduce a second dimension to that, it starts getting ridiculous.

Second point: let's imagine that we can resolve the problem of context overlap so that it's easy for users to think about. There is still the problem of what gets saved as the "enabled" rule set. Let me illustrate. Let's say you have four CCR rules like such:
```
A: global, incompatible w/ C after last reload, last enabled
B: global, incompatible w/ D after last reload, 2nd last enabled
C: app, incompatible w/ A after last reload, non-overlapping context w/ D
D: app, incompatible w/ B after last reload, non-overlapping context w/ C
```
To get into this state, you edited both A and B at the same time, saved, and reloaded. Now, technically here, you can have A+B running as the global CCR rule, and then A+D in D's context, and B+C running in C's context, and there are no problems in terms of spec conflicts. That might even be nice. But now, what the hell do you record as the "active" set? A,B? A,B,C,D? Perhaps more importantly, how do you get the user to think about this easily?

It gets worse. What happens if C's context is (X,Y) and D's context is (X,Z)? See what happens when we add overlapping contexts back in? If we let it get 2-dimensional, the madness kicks in pretty quickly.

Anyway, all this to say, I'm going to put it back to letting app rules KO each other. Then the KO logic is very simple: order of enablement determines winner, nothing more to it than that.

**Comment by kendonB** [comment]
> To get into this state, you edited both A and B at the same time, saved, and reloaded. Now, technically here, you can have A+B running as the global CCR rule AGREE, and then A+C in C's context BUT YOU SAY C IS INCOMPATIBLE WITH A??

Did you get the letters right here?

**Comment by synkarius** [comment]
I did not get the letters right there, no. Thanks, @kendonB.

**Comment by kendonB** [comment]
> To get into this state, you edited both A and B at the same time, saved, and reloaded. Now, technically here, you can have A+B running as the global CCR rule, and then A+D in D's context, and B+C running in C's context, and there are no problems in terms of spec conflicts. That might even be nice. But now, what the hell do you record as the "active" set? A,B? A,B,C,D? Perhaps more importantly, how do you get the user to think about this easily?

I'm not sure I understand the complication here. It seems like the obvious answer is A, B, C, D given the current functionality and caster would just handle the KOing as needed. But will the KO logic be clever enough to allow for the "you can have A+B running as the global CCR rule, and then A+D in D's context, and B+C running in C's context" behavior? Or will it just knock C + D out?
