### ISSUE TITLE
Alternate mouse modes don't work in some circumstances

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#47]
Report received of none of the mouse modes working under Windows 8 on a virtual machine guest on a Mac. Can anyone confirm or advise?

**Comment by Versatilus** [comment]
I'm having the same problem, but I'm using Windows 7 32-bit. I can't give you any helpful information yet. I'm still trying to familiarize myself with the Caster code base, to see what kind of debugging options are available for me and generally where everything happens.

**Comment by synkarius** [comment]
@Versatilus, I just pushed a fix for the grids, 16d2d6506ec90af902a1cf13de7f1c5ebc8d6836. Let me know if that takes care of the issue so I can finally close this one.

**Comment by synkarius** [comment]
Also, I recommend the Pydev remote debugger, since you're running with Dragon NaturallySpeaking like I am.

**Comment by Versatilus** [comment]
Everything seems to be working fine now.

I'll take a look at that debugger. I've been using Emacs, but I'm willing
to try something new. I have no use of my arms right now, so I like how
keyboard focused Emacs is.

**Comment by Zone22** [comment]
I'm working on getting Atom completely controlled by commands. Atom is keyboard focus by default. About the most customizable editor outside of Emacs and it's modern.  That being said you check out my for Castor repository for details. if you have any requests regarding functionality I'll see if I can implement it as soon as possible.
