### ISSUE TITLE
Continuous Commands

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#50]
Meaning you can speak various commands all in one utterance, and it will get chopped up into separate commands. Thus enforcing the end-user to say something that matches a command and Dragon ignores all other input increasing DNS accuracy. In addition this should lead to faster recognition from DNS

**Comment by synkarius** [comment]
Caster already has CCR. https://github.com/synkarius/caster/wiki/CCR Let me know if you have any questions after reading that.
