### ISSUE TITLE
caster.bat returns Device or resource busy The directory is not empty.

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#51]
At the time of executing the installer or Bat file 'C:\NatLink\NatLink\MacroSystem' is empty.

From command prompt
'C:\NatLink\NatLink\MacroSystem>git clone https://github.com/synkarius/caster.git

Cloning into 'caster'...
remote: Counting objects: 3382, done.
emote: Total 3382 (delta 0), reused 0 (delta 0), pack-reused 3382
Receiving objects: 100% (3382/3382), 14.00 MiB | 5.97 MiB/s, done.
Resolving deltas: 100% (2326/2326), done.
Checking connectivity... done.
mv: cannot move 'caster' to '../caster': Device or resource busy
The directory is not empty.'

**Comment by synkarius** [comment]
Good catch! I originally thought that making that installer was a good idea, but you're not the first person to have trouble with it. I've updated those instructions with a much simpler YouTube version and done away with the installer. 
https://www.youtube.com/watch?list=PLV6JPhkq1x8JNM6Cw02M_cMueGmh9ma50&v=wjSwB4cpMDI
