### ISSUE TITLE
Sikuli scripts does not exist in default Path defined in settings.json

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#54]
The default path in SIKULI_SCRIPTS_FOLDER_PATH does not exist within Caster. The screenshots below contain the Error when restarting Dragon with Sikuli enabled and my current settings. It's quite possible something misconfigured.

https://www.dropbox.com/s/dcogq9j2h4aa5tk/Screenshot%202015-06-11%2010.36.28.png?dl=0
https://www.dropbox.com/s/7xnlngozmwt0jtw/Untitled.png?dl=0

**Comment by synkarius** [comment]
Good catch! This should be fixed in  commit
c3230bfeec662659e2b9def33a2fc511d593da9e
