### ISSUE TITLE
Text Input Not Working

### ISSUE THREAD

**Issue by RobertCorey** [synkarius/caster#55]
Hello, I have everything installed and some parts of the system working. The mouse movement commands are working but I'm not able to input / edit text. I made this video to illustrate https://youtu.be/Cu_TDAl6ZCs . I am guessing there is something I need to change in the configuration files. I jumped right into the quick reference after installing but I'll spend some time going through the project to see if I can figure it out.

**Comment by synkarius** [comment]
Your guess is correct, and you can change it by voice. You used one of the text formatting commands, which is from the navigation module. To enable the navigation module, you can say "enable navigation". You also said "arch", which is from the alphabet module. 

(A quick note about the text formatting commands: they all end with the word "bow". So for example, you said "yell hello world". It should have been "yell bow hello world".)

I apologize for the lack of documentation. I am slowly creating YouTube videos and updating and expanding the wiki, but it's not always easy to find the time. Thank you for helping me user test this software. You and others doing so exposes my erroneous assumptions, like for example, that everyone would magically know about the settings file, and the names of the modules.

As of the most recent update, the four modules responsible for most of the stuff on the quick reference sheet are enabled by default, and it includes an explanation about how to activate the others.

**Comment by synkarius** [comment]
Two other things I should mention: 
(1) that status window in your video is an experimental feature which I didn't mean to leave on by default and
(2) if you upgrade your version by copying the new source over the old source, it won't delete your old settings file, so nothing will be enabled still. The file settings.json is generated the first time you run Caster, or after you delete it.

**Comment by RobertCorey** [comment]
Thanks for your help, it is working now and I was able to write a fizz buzz in JavaScript using mostly my voice! Instead of making formal tutorial videos maybe you could record your normal workflow while using caster, I think seeing in use would really help with those little gotchas.
