### ISSUE TITLE
No method named 'get_rule'  with filename `test.py` when method is present.

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#57]
- Consistently reproducible with the following
1. Create a file named `test.py` in `.caster\rules`
2. Paste in or create any valid rule. Tested with MappingRule and CCRType.APP
3. Start Dragon
4. `No method named 'get_rule' was found on 'test'. Did you forget to implement it?` on startup.
Note: `test.pyc` is not generated

Simply renaming `test.py` to `test1.py` or any other derivative so long as it's not `test`. Then the grammar loads as expected.

Example grammar
```Python
from dragonfly import Key, Dictation, MappingRule, Text

from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.additions import IntegerRefST
from castervoice.lib.merge.state.short import R


class Decker(MappingRule):

    mapping = {
        "hit the deck": R(Text("shipwrecked")), 
        "explosion": R(Text("cannonball"))
    }


def get_rule():
    return Decker, RuleDetails(name="Decker")
```

This explains some of the intermittent `No method named 'get_rule'` issues with reporting as as I have occasionally used `test` as a filename for grammars.

- Consider the following rule regardless of file name and `def get_rule():` method deleted. No error messages generated at all during startup.

```Python
from dragonfly import Key, Dictation, MappingRule, Text

from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.additions import IntegerRefST
from castervoice.lib.merge.state.short import R


class Decker(MappingRule):

    mapping = {
        "hit the deck": R(Text("shipwrecked")), 
        "explosion": R(Text("cannonball"))
    }
```

**Comment by synkarius** [comment]
Interesting. This is happening because somewhere on your PYTHONPATH, in some library somewhere, there is a file named "test.py". I don't think Caster's behavior should change here, but the error message can be made better.
