### ISSUE TITLE
Caster does not initialize properly with windows speech recognition.   

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#59]
1.Launching wsr.py with in the following directory.  

C:\Users\User\Desktop\caster\caster
Import error _caster.py 

2.Launching wsr.py with in the following directory.  

C:\Users\User\Desktop\caster
Import error __init__.py

wsr.py expects to Import __init__.py and _caster.py from the same directory.  

3.When using dfly_loader_wsr.py I pulled from github.The .json files are not found.  

INFO:engine:Selecting audio source: u'Microphone (WO Mic Device)'
INFO:directory:Looking for command modules here: C:\Users\user\Desktop\caster
INFO:directory:Valid paths: C:\Users\user\Desktop\caster\dfly_loader_wsr.py, C:
\Users\user\Desktop\caster\sample.py, C:\Users\user\Desktop\caster\_caster.py
INFO:module:CommandModule('dfly_loader_wsr.py'): Loading module: 'C:\Users\user
\Desktop\caster\dfly_loader_wsr.py'
INFO:module:CommandModule('sample.py'): Loading module: 'C:\Users\user\Desktop\
caster\sample.py'
DEBUG:grammar.load:Grammar sample: adding rule MainRule.
DEBUG:grammar.load:Grammar sample: loading into engine Sapi5InProcEngine().
DEBUG:engine:Loading grammar sample.
DEBUG:grammar.load:Grammar sample: adding rule _IntegerRef_07.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling grammar sample.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule MainRule.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule u'MainRule' (id 1).
DEBUG:grammar.load:Grammar sample: adding rule _IntegerRef_07.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule _IntegerRef_07.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule u'_IntegerRef_07' (id 2).
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule _IntegerRef_07.
DEBUG:engine.compiler:Sapi5Compiler(): Already compiled rule _IntegerRef_07.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule _FakeRule.
DEBUG:engine.compiler:Sapi5Compiler(): Compiling rule u'_FakeRule' (id 3).
DEBUG:grammar.load:Grammar sample: activating rule MainRule.
DEBUG:engine:Activating rule MainRule in grammar sample.
DEBUG:grammar.load:Grammar sample: activating rule _IntegerRef_07.
INFO:module:CommandModule('_caster.py'): Loading module: 'C:\Users\user\Desktop
\caster\_caster.py'

IOError: Could not find settings file: C:/NatLink/NatLink/MacroSystem/caster/bin
/data/settings.json
Initializing file...

(<type 'exceptions.WindowsError'>, WindowsError(3, 'The system cannot find the p
ath specified'), <traceback object at 0x01AF6AA8>)
Attempting to load CCR anyway...
ERROR:module:CommandModule('_caster.py'): Error loading module: No module named
natlink

4.Launching dfly_loader_wsr.py with in the following directory.  

C:\Users\User\Desktop\caster\caster

INFO:engine:Selecting audio source: u'Microphone (WO Mic Device)'
INFO:directory:Looking for command modules here: C:\Users\user\Desktop\caster\c
aster
INFO:directory:Valid paths: C:\Users\user\Desktop\caster\caster\dev.py, C:\User
s\user\Desktop\caster\caster\dfly_loader_wsr.py, C:\Users\user\Desktop\caster\
caster\wsr.py, C:\Users\user\Desktop\caster\caster\__init__.py
INFO:module:CommandModule('dev.py'): Loading module: 'C:\Users\user\Desktop\cas
ter\caster\dev.py'
ERROR:module:CommandModule('dev.py'): Error loading module: No module named cast
er.lib
INFO:module:CommandModule('dfly_loader_wsr.py'): Loading module: 'C:\Users\user
\Desktop\caster\caster\dfly_loader_wsr.py'
INFO:module:CommandModule('wsr.py'): Loading module: 'C:\Users\user\Desktop\cas
ter\caster\wsr.py'
ERROR:module:CommandModule('wsr.py'): Error loading module: No module named natl
ink
INFO:module:CommandModule('__init__.py'): Loading module: 'C:\Users\user\Deskto
p\caster\caster\__init__.py'

I apologize for the poorly formatted post but I'm using a tablet and without Dragan speak or Caster.

**Comment by synkarius** [comment]
This has to do with some restructuring I did about a month ago. WSR worked before that. This should be fixed with 4d6d4b34c6c506d25523783bf8ea21b751c2363f. Open Windows Speech Recognition, *then* run _caster.py itself.

**Comment by Zone22** [comment]
As per your instructions and with a fresh caster folder. 

Take note of this snippet.
'IOError: Could not find settings file: C:/NatLink/NatLink/MacroSystem/caster/bin
/data/settings.json'
caster is looking for settings.json outside the root directory of caster.

Output 
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\User>cd C:\Users\User\Desktop\caster

C:\Users\User\Desktop\caster>_caster.py


IOError: Could not find settings file: C:/NatLink/NatLink/MacroSystem/caster/bin
/data/settings.json
Initializing file...


(<type 'exceptions.WindowsError'>, WindowsError(3, 'The system cannot find the p
ath specified'), <traceback object at 0x01BA1A80>)
Attempting to load CCR anyway...
Traceback (most recent call last):
  File "C:\Users\User\Desktop\caster\_caster.py", line 55, in <module>
    from caster.lib import ccr
  File "C:\Users\User\Desktop\caster\caster\lib\ccr.py", line 17, in <module>
    from caster.lib import control
  File "C:\Users\User\Desktop\caster\caster\lib\control.py", line 2, in <module
>
    from dragonfly.timer import _Timer
  File "C:\Python27\lib\site-packages\dragonfly\timer.py", line 27, in <module>
    import natlink
ImportError: No module named natlink

C:\Users\User\Desktop\caster>

**Comment by synkarius** [comment]
And that was because I had hardcoded the path to the settings file, not thinking about people running it off the desktop or anywhere else. Should be fixed by b4a625be0aa5afcaeac539a8fdd45d3ee182b5ed.

**Comment by synkarius** [comment]
Crap, no it isn't, need one more.

**Comment by Zone22** [comment]
Strangely enough I tried Symbolic link C:\Users\User\Desktop\caster\caster to C:\NatLink\NatLink\MacroSystem\caster

The result being the same error above.

**Comment by synkarius** [comment]
That ought to do it.

**Comment by synkarius** [comment]
You'll have to delete your settings file though, or just make a new Caster folder entirely.

**Comment by synkarius** [comment]
I didn't see the very bottom of your trace. So _Timer requires natlink? That's unfortunate. That cuts out a lot of stuff.

**Comment by synkarius** [comment]
I'm going to have to reimplement _Timer for WSR at some point it seems.

**Comment by synkarius** [comment]
d3328b47428d29d2969685cced66df7d007744fd -- no longer importing _Timer.
