### ISSUE TITLE
Caster with backend WRS requires x version of dragonfly 

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#60]
As per the tutorial installed dragonfly using the following repository. Therefore the Dragonfly version requirements should be satisfied.  

Tutorial dragonfly recommended repository.  
https://github.com/t4ngo/dragonfly

Error Output 
ValueError while loading settings file: C:\Users\User\Desktop\caster\caster\bin
\data\settings.json

(<type 'exceptions.ValueError'>, ValueError('Invalid \\escape: line 55 column 36
 (char 1578)',), <traceback object at 0x01AA3C88>)
*- Starting Caster v 0.4.7 -*

Attempting to load CCR anyway...
Traceback (most recent call last):
  File "C:\Users\User\Desktop\caster\_caster.py", line 54, in <module>
    from caster.lib import ccr, utilities
  File "C:\Users\User\Desktop\caster\caster\lib\ccr.py", line 23, in <module>
    pkg_resources.require("dragonfly >= 0.6.5beta1.dev-r99")
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 741, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: dragonfly>=0.6.5beta1.dev-r99

**Comment by synkarius** [comment]
Can you paste the entire contents of your settings file here? Although it's complaining about Dragonfly, the first thing it complained about was an invalid escape character in your settings file, I assume a backslash. There should only be forward slashes in the settings file.

**Comment by Zone22** [comment]
{
    "auto_com": {
        "active": false, 
        "change_language": false, 
        "change_language_only": false, 
        "executables": [
            "pycharm.exe", 
            "WDExpress.exe", 
            "notepad++.exe"
        ], 
        "interval": 3
    }, 
    "ccr": {
        "common": [], 
        "default_lower": true, 
        "modes": {
            "alphabet": true, 
            "android": false, 
            "c++": false, 
            "html": false, 
            "java": false, 
            "javascript": false, 
            "navigation": true, 
            "numbers": true, 
            "punctuation": true, 
            "python": false, 
            "sequel": false
        }, 
        "registered_extensions": {}, 
        "standard": [
            "alphabet", 
            "navigation", 
            "punctuation", 
            "numbers"
        ]
    }, 
    "miscellaneous": {
        "debug_speak": false, 
        "dev_commands": false, 
        "sikuli_enabled": false, 
        "status_window_enabled": false
    }, 
    "nodes": {}, 
    "one time warnings": {}, 
    "password": {
        "seed1": "change these", 
        "seed2": "if you use", 
        "seed3": "password", 
        "seed4": "generation"
    }, 
    "paths": {
        "ALARM_SOUND_PATH": "C:/Users/User/Desktop/caster/caster/bin/media/49685__ejfortin__nano-blade-loop.wav", 
        "ALIASES_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/ccr/configaliases.txt", 
        "BASE_PATH": "C:/Users/User/Desktop/caster/caster", 
        "DEFAULT_BROWSER_PATH": "C:/Users/User/Desktop/Share/PortableApps/FirefoxPortable/FirefoxPortable.exe", 
        "DISPEL_JSON_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/dispel.json", 
        "DLL_PATH": "C:/Users/User/Desktop/caster/caster/lib/dll/", 
        "DOUGLAS_PATH": "C:/Users/User/Desktop/caster/caster/asynch/mouse/grids.py", 
        "ENGINE_PATH": "C:/Program Files (x86)/Nuance/NaturallySpeaking12/Program/natspeak.exe", 
        "GENERIC_CONFIG_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/ccr", 
        "HOMUNCULUS_PATH": "C:/Users/User/Desktop/caster/caster/asynch/hmc/h_launch.py", 
        "LEGION_PATH": "C:/Users/User/Desktop/caster/caster/asynch/mouse/legion.py", 
        "LOG_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/log.txt", 
        "MEDIA_PATH": "C:/Users/User/Desktop/caster/caster/bin/media", 
        "PITA_JSON_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/pita.json", 
        "RAINBOW_PATH": "C:/Users/User/Desktop/caster/caster/asynch/mouse/grids.py", 
        "REBOOT_PATH": "C:/Users/User/Desktop/caster/caster/bin/reboot.bat", 
        "RECORDED_MACROS_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/recorded_macros.json", 
        "REMOTE_DEBUGGER_PATH": "C:/PROG/alt ec/eclipse/plugins/org.python.pydev_3.9.2.201502050007/pysrc", 
        "SAVED_CLIPBOARD_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/clipboard.json", 
        "SETTINGS_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/settings.json", 
        "SIKULI_COMPATIBLE_JAVA_EXE_PATH": "", 
        "SIKULI_IDE_JAR_PATH": "", 
        "SIKULI_SCRIPTS_FOLDER_PATH": "C:/Users/User/Desktop/caster/caster/asynch/sikuli/scripts", 
        "SIKULI_SCRIPTS_JAR_PATH": "", 
        "SIKULI_SERVER_PATH": "C:/Users/User/Desktop/caster/caster/asynch/sikuli/scripts/xmlrpc_server.sikuli", 
        "STATUS_WINDOW_PATH": "C:/Users/User/Desktop/caster/caster/asynch/statuswindow.py", 
        "STICKY_LIST_PATH": "C:/Users/User/Desktop/caster/caster/asynch/stickylist.py", 
        "S_LIST_JSON_PATH": "C:/Users/User/Desktop/caster/caster/bin/data/s_list.json", 
        "WSR_PATH": "C:/Windows/Speech/Common/sapisvr.exe"
    }, 
    "pita": {
        "automatic_lowercase": true, 
        "extensions": [
            ".py", 
            ".java", 
            ".cpp", 
            ".h", 
            ".js"
        ], 
        "filter_strict": false, 
        "recent_files": 10, 
        "use_bonus": true, 
        "use_penalty": true
    }, 
    "pronunciations": {
        "c++": "C plus plus", 
        "jquery": "J query"
    }
}

**Comment by Versatilus** [comment]
I ran into the same problem last night when I was forced to reinstall Python. The problem is that Python doesn't have any package information registered for Dragonfly when it is installed by copying the directory from the repository.

I solved the problem for myself by copying the whole repository to a permanent location(in my case C:\Programming\dragonfly\) and running the included build_develop.py. .

**Comment by Zone22** [comment]
That makes a lot of sense. I don't think I copy and paste the dragonfly repository into my python lib/site packages directory. Nevertheless I must've. Will test soon.





On June 21, 2015 11:14:39 AM CDT, Versatilus <notifications@github.com> wrote:
>I ran into the same problem last night when I was forced to reinstall
>Python. The problem is that Python doesn't have any package information
>registered for Dragonfly when it is installed by copying the directory
>from the repository.
>
>I solved the problem for myself by copying the whole repository to a
>permanent location(in my case C:\Programming\dragonfly\) and running
>the included build_develop.py. .
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/synkarius/caster/issues/60#issuecomment-113921400

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by synkarius** [comment]
So far, I've been unable to reproduce this. I uninstalled Natlink, moved a copy of Caster to my desktop, and deleted all my settings and other json files. Doing this, everything worked fine. That puzzles me more than the rest.

I also tried a fresh install of Dragonfly and Caster on a virtual machine. Doing that, I got some other errors which I'll be looking into and have partially fixed already. I'm surprised at how much of Dragonfly is Natlink-dependent. More later, but hopefully Versatilus's solution works for you.

**Comment by Zone22** [comment]
@Versatilus
Quick question By chance on the computer that you experienced the error you never installed natlink or dragon? That would also imply that you using WSR as a backend for speech recognition?

**Comment by Versatilus** [comment]
I'm using Natlink and Dragon. The problem I had involving Dragonfly's
version number didn't have anything to do with the speech engine I was
using. It was just related to the way that I had installed Dragonfly. I had
copied my Dragonfly directly from my previous installation of Python to the
new one because I customized a few things like adding support for the mouse
wheel.

**Comment by Zone22** [comment]
Fixed with Versatilus's solution.

**Comment by synkarius** [comment]
@Zone22, did you also install Dragonfly by copying it? I'm pleased but somewhat amazed that this worked.

**Comment by Zone22** [comment]
@synkarius 
lt was more involved than just copy and paste.
I reinstalled python including all the dependencies for Dragonfly. Then I copied and pasted the dragonfly repository to C:\Python27\Lib\site-packages. Executed build_develop.py from dragonfly repository and pip.bat from caster repository.
