### ISSUE TITLE
rules.toml is not being written correctly on enable/disable

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#61]
To reproduce:
1. Wipe out user folder.
2. Start Dragon/caster
`_enabled_ordered` shows:
```
_enabled_ordered = ["Alphabet", "Navigation", "Numbers", "Punctuation", "CasterRule", "HardwareRule", "MouseAlternativesRule", "WindowManagementRule", "LegionGridRule", "DouglasGridRule", "RainbowGridRule", "HMCRule", "HMCConfirmRule", "HMCDirectoryRule", "HMCHistoryRule", "HMCLaunchRule", "HMCSettingsRule", "DragonRule", "BringRule", "GrammarActivatorRule", "HooksActivationRule"]
```
2. Say "enable r"
3. Say "enable python" (conflicts with r but nothing else)
4. Almost everything gets knocked out and `_enabled_ordered` becomes:
```
_enabled_ordered = ["Alphabet", "Navigation", "Numbers", "Punctuation", "BringRule", "Python", "PythonNon"]
```

**Comment by kendonB** [comment]
I noticed this when I created two app context MergeRules which had conflicting specs but nonoverlapping contexts so they shouldn't have gotten knocked out at all. Might be a separate bug

I also recommend keeping both conflicting rules in `_enabled_ordered` so that if the user disables one the other remains for the next session.

**Comment by synkarius** [comment]
@kendonB @LexiconCode

There are two issues here, including @kendonB's second comment.

1) Companion rules getting KO'd. If this is different from old Caster, I will change it back. I'm away from my Windows PC right now and so can't test this but if you guys are able to test it before I get to it (maybe Wednesday), let me know. If this isn't different from old Caster but we still decide it is not the best way for it to be, I will direct you guys to where to make the changes.

2) Overlapping contexts. @kendonB -- to answer your question from #61, old Caster and new Caster both do not take contexts into account during merges. They only take specs into account. Adding a feature to make them take overlapping contexts into account is well beyond the scope of this rewrite. However, if anyone would like to tackle that feature, the good news is, new Caster is far more accommodating to that kind of enhancement. You would need to create an alternate compatibility checker and an alternate merge strategy, and then replace the default implementations with them or perhaps make them opt-in or opt-out settings. (There _will_ be performance consequences -- I'm not sure if they'll be negligible or noticeable, depends on how Dragonfly handles contexts, and I haven't tested that extensively.)

I strongly recommend _against_ keeping both rules in `_enabled_ordered` unless you really understand what that means and the additional work that will entail. (In my opinion, you'd be better off creating another section in rules.toml which was like, "rules I tried to have enabled simultaneously" or something like that, and then let Caster figure it out at the next boot or merge.)

**Comment by kendonB** [comment]
I've updated the original comment to show that the KO behavior for sure isn't right.

**Comment by kendonB** [comment]
It looks like the stuff doesn't actually get knocked out within the caster session and only actually get knocked out upon a reboot. e.g. "legion" after the final step still works.

**Comment by kendonB** [comment]
I have been able to work around have CCR commands in different contexts with the same spec by just altering the spelling of one "line" -> "lyne" for example.

I think going forward we will just handle these with parent rules and `ContextAction`

**Comment by kendonB** [comment]
it seems to be inadvertently deleting all of the non-CCR rules from the rules.toml file

**Comment by synkarius** [comment]
@kendonB 

Hmm. That's not good. Thank you for the thorough testing and pinpointing the issue for me. I have an idea what the problem might be, should be able to test it tomorrow.

What do you mean about "parent rules" and `ContextAction`?

**Comment by kendonB** [comment]
> What do you mean about "parent rules" and `ContextAction`?

I mean using a global/multi-context CCR rule and using calls to `ContextAction` to manage differences across individual contexts.

**Comment by synkarius** [comment]
That can solve the problem in the short term. I don't think it's a good solution in the long term because: 
1. it not only unnecessarily crowds the global spec space with stuff that could be in the contextual spec spaces (and encourages others to do so since new rules are often copy/paste + modify), thus leading to complexity errors faster than necessary, but also
2. there will have to be a **lot** of no-op actions to go with that. For instance, if I have two commands, one which both Eclipse and IntelliJ do, and another one which only IntelliJ does, the action for the IntelliJ-only command will have to be no-op (probably a `NullAction`) not only in Eclipse, but literally everywhere else except IntelliJ. (And for that matter, the Eclipse/IntelliJ command will have to have a no-op action everywhere else, still consuming a spec -- a probability recognition boost-- but doing nothing.)

**Comment by synkarius** [comment]
@kendonB Following up with my last comment about the downsides of overusing `ContextAction`:

I'm not sure what the downsides of creating alternate implementations to the default compat checker and merge strategy would be. Is there a reason you don't want to do that?

**Comment by synkarius** [comment]
Ah. @kendonB I misread what you were saying earlier. You weren't debating the merits of companion rules getting KO'd along with their CCR rules. You were saying that in your example, _only_ the Python companion should get KO'd not the Navigation companion. I get it now. Sorry about the miscommunication.

**Comment by kendonB** [comment]
> I'm not sure what the downsides of creating alternate implementations to the default compat checker and merge strategy would be. Is there a reason you don't want to do that?

The big downside is the developer time to get it right. Other than that I don't see an issue with that approach.

**Comment by synkarius** [comment]
> The big downside is the developer time to get it right. Other than that I don't see an issue with that approach.

I would be happy to guide anyone willing to take that on. The difficult parts are the conceptual parts I discussed in #46, but the part of it which is just getting the code where it's supposed to be is quite easy.

Compatibility checkers should inherit from BaseCompatibilityChecker. (This is so that Python 3 type hinting doesn't hinder inversion of control.) SimpleCompatibilityChecker does so and is only 33 lines long.

Merge strategies should inherit from BaseMergingStrategy. (Same reason as above.) ClassicMergingStrategy does so and is only 44 lines long. 

SimpleCompatibilityChecker and ClassicMergingStrategy are both injected into the new CCRMerger in the Nexus. This is where the new setting would be applied to swap out these two default implementations with two alternate implementations.

These are of course only recommendations.

**Comment by synkarius** [comment]
FYI, I _am_ working on the main issue in this one (rule.toml getting written incorrectly). It's just a little complicated, and I haven't had much time this past week or so.

**Comment by synkarius** [comment]
@kendonB @LexiconCode, this should be good to go.

**Comment by LexiconCode** [comment]
The following trace back occurs when you try to disable a rule that has not been able to yet or no longer enabled.

Test procedure
if `r` rule `is` enabled saying `disable r` `twice`

or

if `r` rule is `not` enabled saying `disable r` `once``

```
ERROR:action:Exception from function <lambda>:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_activator.py", line 62, in <lambda>
    _mapping[disable_spec] = Function(lambda rcn: self._activation_fn(rcn, False), rcn=class_name)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 75, in <lambda>
    self._activator.set_activation_fn(lambda rcn, active: self._change_rule_enabled(rcn, active))
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 152, in _change_rule_enabled
    self._rewrite_config_file(enabled_diff)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 175, in _rewrite_config_file
    result.remove(rcn)
ValueError: list.remove(x): x not in list
ERROR:action.exec:Execution failed: Function(<lambda>): list.remove(x): x not in list
```

**Comment by synkarius** [comment]
@LexiconCode Nice catch. It's a simple fix. I can get to that tonight, or even this afternoon maybe.

**Comment by synkarius** [comment]
@LexiconCode That should be good now. Also, thanks for updating Travis.

**Comment by LexiconCode** [comment]
@kendonB this seems to work for me, can you confirm?
