### ISSUE TITLE
Content loader does not import filenames with decimals 

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#62]
It's unusual to have decimals/period in file names and may be behavior of Python importing rather than a bug explicit caster code.

Reproduce
1. Create any valid rule in `.caster\rules`.
2. Name the file any derivative with a number and decimal. File name examples below...
- foo_grammar-0.0.py
- bar_bogus3.1.py
- focus_grammar_1.6 .py
- 53.6focus_grammar.py
3. Produces 'ImportError: No module named <whatever_you_named_your_grammar.py>'

Note `bar_bogus1.py` loads as expected.

Example grammar with the filename `Decker1.0.py`
```Python
from dragonfly import Key, Dictation, MappingRule, Text

from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.additions import IntegerRefST
from castervoice.lib.merge.state.short import R


class Decker(MappingRule):

    mapping = {
        "hit the deck": R(Text("shipwrecked")), 
        "explosion": R(Text("cannonball"))
    }


def get_rule():
    return Decker, RuleDetails(name="Decker")
```

Full Traceback
```
Could not import 'Decker1.0'. Module has errors: Traceback (most recent call last):
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 121, in _import_module
    return load_fn(module_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Decker1.0
```

**Comment by synkarius** [comment]
Generally, module names don't include periods.
https://stackoverflow.com/questions/1828127/how-to-reference-python-package-when-filename-contains-a-period

If you want to version them, use underscores: "decker1_0.py" and so forth.
