### ISSUE TITLE
How do we get "reload all rules" to work?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#63]
I can see it [here](https://github.com/synkarius/Caster/blob/ccrmerger2/castervoice/lib/ctrl/mgr/loading/reload/manual_reload_observable.py) but it doesn't work for me. 

I have tried both "reload all rules" and "enable caster manual grammars reload command rule".

**Comment by LexiconCode** [comment]
Open `settings.toml` 

```[miscellaneous]
reload_trigger = "timer"```

Change 'timer' to `manual`

**Comment by kendonB** [comment]
Mm so there's no option for both? When a grammar has an error upon the initial load we have to reboot the engine to load it.

**Comment by LexiconCode** [comment]
Grammars have to load successfully initially during boot for them to be able to reload by timer or manually. So you are correct we do have to reboot the engine.

**Comment by kendonB** [comment]
I wonder if there's a way to make them load as empty initially to get around this
