### ISSUE TITLE
Reimplement Missing WSR Functionality

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#63]
- [x] _Timer
- [x] RecognitionHistory
- [x] BoxAction

~~64 bit Windows scanning patch (not really related)~~

**Comment by Zone22** [comment]
How has this a limited WSR Functionality with Caster? I don't want to start reporting Issues that might stem out of missing _Timer, RecognitionHistory, and the 64-bit window scanning patch.

**Comment by synkarius** [comment]
_Timer affects at least the ergonomic alarm, Sikuli, and AsynchronousAction, maybe more, can't think of others presently. RecognitionHistory affects the "again" and "record from history" commands. The window scanning thing affects anything which uses executable names to figure out context. That one is less severe because you can also use window title and that works, but it's still incomplete.

All that said, there may be stuff I don't know about yet, so please don't feel limited in reporting any bugs you may run into.

**Comment by synkarius** [comment]
_Timer also affects anything that pops up a text window.

**Comment by synkarius** [comment]
Window monkey patch from commit af7aff713bda531177e97c3723e0829fe7c0c089 means Natlink is no longer required for window executable scanning.

**Comment by synkarius** [comment]
Removed Window monkey patch, as it doesn't solve the problem.

**Comment by synkarius** [comment]
TimerForWSR doesn't work perfectly yet; at present, you can't interrupt it.

**Comment by synkarius** [comment]
Also, this has brought it to my attention that BoxAction and anything else which attempts to launch an external process isn't working in WSR, so that has been added to the list at the top.

**Comment by synkarius** [comment]
TimerForWSR actually does work perfectly. The problem with my tests before was that I was using the word "cancel" to interrupt it. WSR hijacks "cancel", so I've set the `rspec` of the "clear" command so that it can also be used to cancel AsynchronousActions.

**Comment by synkarius** [comment]
BoxAction works too. I wonder if I just had the microphone volume too low before.

**Comment by synkarius** [comment]
AFAICT, Windows Speech Recognition has no equivalent of Natlink's RecognitionHistory. However, Caster's ContextStack is platform agnostic and captures the words spoken in commands. It doesn't and can't capture free dictation, but except for that, it could be used to replace RecognitionHistory.

**Comment by chilimangoes** [comment]
Looking at the referenced commit, I don't understand how changing the "rspec" of the clear command to "cancel" makes it so you can use it to cancel AsyncActions.

**Comment by synkarius** [comment]
Sorry. My comment was innaccurate there. I meant that I could use "clear" to cancel the "jump in" action, which was the one I was testing with. The "clear" command won't cancel *any* AsynchronousAction, just those which list the `rspec` "cancel" as a termination-word in their first ContextLevel's ContextSet (which is most of the cancelable commands, hence the inaccuracy in the earlier comment). So for instance, the "never-ending" command in dev.py won't be canceled by "clear", but rather by "ashes" and "bravery". Had I been using it to test instead of the "jump in" command, I would have realized the problem sooner.
