### ISSUE TITLE
RegisteredAction with anything beyond R(Key("X") can keep macros from triggering.

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#67]
When creating shortcut macros for Atom. I discovered that when using a RegisteredAction beyond R(Key("X") causes the macro to become nonfunctional and not throw an error when loading caster.

For instance A. The command is recognized but the macro is not triggered.

A. [go to] line <n>":        R(Key("c-g") + Pause("10") + Text("%(n)s") + Key("enter"), rdescript="Atom: Go to Line #"),

For B. The command and the macro is recognized and the macro is triggered. Everything functions as expected.

B. [go to] line <n>":         Key("c-g") + Pause("10") + Text("%(n)s") + Key("enter"),

Using  A. I've tested each "+ Pause("10")"  "+ Text("%(n)s")"  "+ Key("enter")"  individually with Key("c-g")
Regardless of the combination or exclusion they all produce the same result as described in A.

**Comment by synkarius** [comment]
I know about and am looking into this one. It's a pretty significant shortcoming of the context stack, so I'm going to fix it next.

**Comment by synkarius** [comment]
Note to self: RegisteredActions have to account for the wrapped object being an ActionSeries or ActionRepetition.

**Comment by synkarius** [comment]
Will take care of this after work tomorrow. Late now.
