### ISSUE TITLE
[WSR] Legion feature not available without PIL

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#69]
The error can be reproduced after legion command is recognized by WSR through repetition of the command. The sound meter in WSR does not register sound. In addition WSR no longer receives a dictation slash commands. WSR at this point has not frozen.  PIL dependency seems to be installed via pip.bat and correctly placed within Python.

At this point If WSR was not restarted but Caster was it would produce the error below. WSR completely locks up and has to be terminated by the task manager.

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\System32>C:\Users\User\Desktop\Caster.lnk
*- Starting Caster v 0.4.9 -*
No handlers could be found for logger "engine.sapi5"

Attempting to load CCR anyway...
<class 'dragonfly.engines.base.engine.EngineError'>
No usable engines found.
<traceback object at 0x01CF1620>
  File "C:\Users\User\Documents\GitHub\caster\_caster.py", line 26, in <module>

    from caster.lib.dfplus.state import stack# requires control

  File "C:\Users\User\Documents\GitHub\caster\caster\lib\dfplus\state\stack.py"
, line 126, in <module>
    control.nexus().inform_state(CasterState())

  File "C:\Users\User\Documents\GitHub\caster\caster\lib\control.py", line 101,
 in nexus
    _NEXUS = Nexus()

  File "C:\Users\User\Documents\GitHub\caster\caster\lib\control.py", line 77,
in __init__
    self.macros_grammar = Grammar("recorded_macros")

  File "C:\Python27\lib\site-packages\dragonfly\dragonfly\grammar\grammar_base.p
y", line 81, in __init__
    self._engine = get_engine()

  File "C:\Python27\lib\site-packages\dragonfly\dragonfly\engines\__init__.py",
line 86, in get_engine
    raise EngineError("No usable engines found.")

exception: No usable engines found.
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly\\dragonfly\\config.py', 242
, 'load_from_file', 'execfile(path, namespace)')
frame: ('C:/Users/User/Documents/GitHub/caster/caster/bin/data/ccr/configpunctu
ation.txt', 13, '<module>', '"semper":\t\t\t\t\t\tR(Key("semicolon"), rdescript=
"Semicolon"),')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\dfplus\\state
\\actions.py', 14, '__init__', 'self.state = control.nexus().state')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\control.py',
101, 'nexus', '_NEXUS = Nexus()')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\control.py',
77, '__init__', 'self.macros_grammar = Grammar("recorded_macros")')
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly\\dragonfly\\grammar\\gramma
r_base.py', 81, '__init__', 'self._engine = get_engine()')
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly\\dragonfly\\engines\\__init
__.py', 86, 'get_engine', 'raise EngineError("No usable engines found.")')
exception: No usable engines found.
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly\\dragonfly\\config.py', 242
, 'load_from_file', 'execfile(path, namespace)')
frame: ('C:/Users/User/Documents/GitHub/caster/caster/bin/data/ccr/configalphab
et.txt', 5, '<module>', 'from caster.lib import navigation')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\navigation.py
', 12, '<module>', 'from caster.lib.pita import scanner, selector')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\pita\\scanner
.py', 16, '<module>', 'if control.nexus().dep.NATLINK:')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\control.py',
101, 'nexus', '_NEXUS = Nexus()')
frame: ('C:\\Users\\User\\Documents\\GitHub\\caster\\caster\\lib\\control.py',
77, '__init__', 'self.macros_grammar = Grammar("recorded_macros")')
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly\\dragonfly\\grammar\\gramma
r_base.py', 81, '__init__', 'self._engine = get_engine()')
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly\\dragonfly\\engines\\__init
__.py', 86, 'get_engine', 'raise EngineError("No usable engines found.")')
<type 'exceptions.KeyError'>
u'numbers'
<traceback object at 0x02B8BC88>
  File "C:\Users\User\Documents\GitHub\caster\caster\lib\ccr.py", line 176, in
initialize_ccr
    set_active(r)

  File "C:\Users\User\Documents\GitHub\caster\caster\lib\ccr.py", line 211, in
set_active
    if settings.SETTINGS["ccr"]["modes"][r] and not merge_copy_compatible(target
_rule_pair[0], rule_pairs[r][0]):

Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\caster\_caster.py", line 82, in <module>

    class MainRule(MappingRule):
  File "C:\Users\User\Documents\GitHub\caster\_caster.py", line 100, in MainRul
e
    "reboot dragon":                R(Function(utilities.reboot), rdescript="Reb
oot Dragon Naturallyspeaking"),
NameError: name 'R' is not defined

C:\Windows\System32>

Some of the testing produced 'No handlers could be found for logger "action"' after  'Legion feature not available without PIL' before WRS froze. This was only reproduced with the caster cmd window In the foreground and the desktop.

**Comment by synkarius** [comment]
This is another of the errors I ran into on my virtual machine install, I think. However, if this is the same thing I ran into, I was able to resolve it. Try looking at these two lines in your Dragonfly install:
https://github.com/t4ngo/dragonfly/blob/f7d1482e3d751bd16faef0f932b4e3cc009688a5/dragonfly/actions/_generate_typeables.py#L117
https://github.com/t4ngo/dragonfly/blob/f7d1482e3d751bd16faef0f932b4e3cc009688a5/dragonfly/actions/typeables.py#L193
Do both of those lines exist in your Dragonfly install? One of them was missing in mine, can't remember which. It was resolved by reinstalling Dragonfly, oddly.
