### ISSUE TITLE
User content isn't being loaded.

### ISSUE THREAD

**Issue by Versatilus** [synkarius/Caster#7]
I copied the navigation CCR rule `C:\NatLink\NatLink\MacroSystem\castervoice\lib\ccr\core\nav.py` over to my user directory `C:\Users\User\.caster\rules\nav.py` and the changes I made in the file weren't loaded. I eventually tracked the issue down to here.
https://github.com/synkarius/Caster/blob/6d842f453e4c087013fb50c537939c7f411026ba/castervoice/lib/ctrl/mgr/loading/load/content_loader.py#L93
The starter modules are added to the system path before the user modules are. Because the rules are loaded by module name instead of filename, the module found in the path first is loaded. Inserting the module directories at the front of the system path fixes the problem of user content not loading, though I haven't gone through the code enough yet to know if that's ultimately the right solution.

**Comment by synkarius** [comment]
Hmm. Thank you for doing that much of the legwork for me. That helps a lot. That may be the right solution. Depends on whether I'm doing that before or after scanning for modules, have to check on that. (Intuitively, I would think that I'd be scanning first, then appending things to the classpath...)

**Comment by synkarius** [comment]
That is in fact the correct solution.
