### ISSUE TITLE
Confirm Command Popup Window

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#78]
A command that's been recognized is halted in its execution until it's confirmed or canceled in a pop-up window. Some commands can be dangerous if unintentionally executed. Even with the phonetically distinct words and other precautions there is a chance of triggering a command that has at least unwanted or at most irreversible effects. 

1. command spoken
2. pop-up window to 'confirm' or 'cancel' (The only commands available for recognition)
3. on confirmation execute the rest of the command or cancels

Thoughts on incorporating it as a general action object?
 "git delete remote branch":             R(Confirm=True, Key("c-i"), rdescript="Atom: Git Delete Remote Branch"),

**Comment by synkarius** [comment]
This could be built from the Homunculus class and the AsynchronousAction. It does seem like a very useful thing to have as a general action object though. I bet I can whip this up pretty quick. I'll see what I can do with it tomorrow.

**Comment by synkarius** [comment]
See the example in [dev.py](https://github.com/synkarius/caster/blob/master/caster/dev.py).

**Comment by synkarius** [comment]
Also, this is only going to work with Dragon until I fix #63 .

**Comment by Zone22** [comment]
it looks like the latest updat doesn't initialize. Testing the clean install of Caster.
"No module named hmc_confirm" 


Attempting to load CCR anyway...
<type 'exceptions.ImportError'>
No module named hmc_confirm
<traceback object at 0x0BC7FEB8>
  File "D:\NatLink\NatLink\MacroSystem\_caster.py", line 17, in <module>
    from caster.apps import *

  File "D:\NatLink\NatLink\MacroSystem\caster\apps\dragon.py", line 5, in <module>
    from caster.asynch.hmc import vocabulary_processing

  File "D:\NatLink\NatLink\MacroSystem\caster\asynch\hmc\vocabulary_processing.py", line 14, in <module>
    from caster.asynch.hmc import h_launch, homunculus

  File "D:\NatLink\NatLink\MacroSystem\caster\asynch\hmc\h_launch.py", line 13, in <module>
    from caster.asynch.hmc.hmc_confirm import Homunculus_Confirm

exception: No module named hmc_confirm
frame: ('C:\\Python27\\lib\\site-packages\\dragonfly-0.6.6b1-py2.7.egg\\dragonfly\\config.py', 242, 'load_from_file', 'execfile(path, namespace)')
frame: ('D:/NatLink/NatLink/MacroSystem/caster/bin/data/ccr/confignavigation.txt', 3, '<module>', 'from caster.lib.pita import fn')
frame: ('D:\\NatLink\\NatLink\\MacroSystem\\caster\\lib\\pita\\fn.py', 3, '<module>', 'from caster.lib.pita import scanner, selector')
frame: ('D:\\NatLink\\NatLink\\MacroSystem\\caster\\lib\\pita\\scanner.py', 10, '<module>', 'from caster.asynch.hmc import h_launch')
frame: ('D:\\NatLink\\NatLink\\MacroSystem\\caster\\asynch\\hmc\\h_launch.py', 13, '<module>', 'from caster.asynch.hmc.hmc_confirm import Homunculus_Confirm')
No handlers could be found for logger "config"
Error loading _caster from D:\NatLink\NatLink\MacroSystem\_caster.py
Traceback (most recent call last):
  File "D:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 340, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "D:\NatLink\NatLink\MacroSystem\_caster.py", line 54, in <module>
    class MainRule(MappingRule):
  File "D:\NatLink\NatLink\MacroSystem\_caster.py", line 67, in MainRule
    "volume <volume_mode> [<n>]":   R(Function(navigation.volume_control, extra={'n', 'volume_mode'}), rdescript="Volume Control"),
NameError: name 'R' is not defined
-- skip unchanged wrong grammar file: D:\NatLink\NatLink\MacroSystem\_caster.py
-- skip unchanged wrong grammar file: D:\NatLink\NatLink\MacroSystem\_caster.py
natlinkmain started from D:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1mike
  DNS version: 13
  Python version: 27
  Windows Version: 8

**Comment by synkarius** [comment]
Sorry about that, forgot to add the file before pushing. d848af2dcc5128a5ed25f8c4f97df5c9962d46cb

**Comment by Zone22** [comment]
Everything runs as expected.

**Comment by synkarius** [comment]
--except that all the popup windows (including ConfirmAction) are broken. I really need to rewrite that section. Fixing, will push momentarily.

**Comment by Zone22** [comment]
I guess what I meant by everything that was it loaded :)

**Comment by synkarius** [comment]
Didn't want to leave ya with a broken version. :)

I'll get this feature working for WSR first thing after I finish the last two Version 0.5.0 features, (semi-)voice control of the settings window and fuzzy string matching for window switching.

**Comment by synkarius** [comment]
Also, sometimes Dragonfly fails to focus the popup. It's maybe 1 in 10 times, but when that occurs, you have to focus it (by clicking or voice command) to be able to say "confirm" or "cancel".

**Comment by Zone22** [comment]
As of yet in my limited testing have experienced that but good to know. Thanks for the late-night code cracking!

This concept implemented slightly different could be used for confirming the recognition of free dictation in a string of action objects. I'll open up a new issue when I have an example and the logic figured out.
