### ISSUE TITLE
Extend NodeRule to any Dragonfly action

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#79]
* make it do more than Text

**Comment by synkarius** [comment]
I realized, partially because of your reaction, that the way I set up the HintNode constructor was rather unintuitive, so I reworked it. It's more similar to a MappingRule now, spec first, then a Dragonfly action, then children, then extras, then defaults.

**Comment by Zone22** [comment]
Hey, it's an improvement! There's a little trade-off in terms of readability versus efficiency. Really that's inconsequential. When I have more free time review the code a little more and see what I can whip up. 

Overall using the MappingRule as a model or even better incorporating features into MappingRule is something that should be given some thought. Not only does it increase the readability but also the reusability of code. Ideally the more centralized features can be within the CCR and apps folder the better.
