### ISSUE TITLE
Extend AsynchronousAction to include general action objects.

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#81]
Extend AsynchronousAction to include general action objects. 

  "never-ending":                 AsynchronousAction([L(S(["ashes", "charcoal"], print_time, None),
                                                      S(["bravery"], Text, "bravery1"))
                                                   ], time_in_seconds=0.2, repetitions=20),

**Comment by synkarius** [comment]
AsynchronousAction has a new optional parameter, "finisher", which is a Dragonfly action to execute after it's finished doing whatever it's doing (waiting, searching, etc.)
