### ISSUE TITLE
find a way to consistently focus windows

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#85]
* research: [stackoverflow](http://stackoverflow.com/questions/15422274/switching-windows-with-python), [stackoverflow](http://stackoverflow.com/questions/6312627/windows-7-how-to-bring-a-window-to-the-front-no-matter-what-other-window-has-fo), [google code](https://code.google.com/p/dragonfly/issues/detail?id=10)
* I'm not opposed to adding pywinauto as a dependency if it can actually get the job done.
* must work on 32 and 64-bit programs, title and executable, Windows 7 and forward

**Comment by synkarius** [comment]
The solution is to use @daanzu's [patch](https://github.com/t4ngo/dragonfly/pull/41.patch) until it becomes accepted as part of Dragonfly.

**Comment by Zone22** [comment]
Would you consider incorporating the patch in your fork of Dragonfly? Then referencing in the caster wiki your fork until the patch becomes accepted as part of Dragonfly. Therefore simplifying the install procedure for newcomers.

**Comment by synkarius** [comment]
Good idea. My fork now has the patch, and a page has been added to the wiki and an annotation to the YouTube install video.
