### ISSUE TITLE
Change dragon modes based on active focused window.

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#89]
In terms of user experience it would be convenient to automatically switch between dragon modes based on active focused window. For instance when an IDE or text editor is active "command" mode would be initiated. If the user minimizes and brings brings up a word processor or a web browser "command and dictation" mode would be activated and possibly deactivating CCR's. Which of course could be manually override.

I believe we have something similar for CCR modules based on launching an application?

**Comment by synkarius** [comment]
We do have something similar for the CCR modules. It also does command mode, exactly like you're describing. There's a section of the settings file that looks like this:

    "auto_com": {
        "active": true, 
        "change_language": true, 
        "change_language_only": false, 
        "executables": [
            "AptanaStudio3.exe", 
            "pycharm.exe", 
            "notepad++.exe", 
            "javaw.exe", 
            "eclipse.exe", 
            "studio64.exe"
        ], 
        "interval": 2
    }

Here are what the values do.

`active`: switches to command mode for executables listed in the `executables` section
`change language`: you guessed it, switches CCR module -- for this to work, the CCR module has to  "register" itself like so:

    settings.register_language(".cpp", "c++")
    settings.register_language(".h", "c++")

`change language only`: language and not command mode
`interval` - time in seconds for pinging the foreground window
