### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#91]
@Zone22, @Versatilus, @chilimangoes, @j127, @chajadan

Since Github doesn't have private messaging, this will be the official announcement thread. If I tagged you in this message, it's because you forked Caster. 

Two announcements to start:

* There is a new branch, "develop". If you're working on anything new, please make the pull request for develop. 

* All IntegerRefs across the whole project have been changed into IntegerRefSTs. This allows for easy remapping of the words which correspond to digits. (So for example, now Nils Klarlund's Short Talk digits are possible.) A new setting (misc/integer_remap) has been added, which is turned off by default, and which activates this remapping.

**Comment by chilimangoes** [comment]
Roger that. It would probably be a good idea to add a "Contributing" section to the main readme file where future potential contributors will see it.

**Comment by synkarius** [comment]
Good idea. It's up.

**Comment by synkarius** [comment]
One more announcement. Caster now has a [ReadTheDocs page](http://caster.readthedocs.org/en/latest/). So far, it's just a copy of the wiki, but eventually I'll be taking the wiki down except for the home page, which will link to ReadTheDocs. There are a couple reasons for this.

1. The documentation is more portable this way.
2. It's easier to add documentation: just create a markdown file and do a pull request, and it automatically shows up on the ReadTheDocs page.
3. ReadTheDocs pages lend themselves better to organization than Github wiki pages.

**Comment by Zone22** [comment]
Include in the ReadTheDocs page names of undocumented features.

Consider using https://slack.com/ or any other platform which has integration with Github as a hub for the community. Leaving Github strictly for issues regarding Caster.

**Comment by j127** [comment]
> If I tagged you in this message, it's because you forked Caster.

Thanks... I'm interested in contributing, but I haven't had time to look at it closely yet.

> Consider using https://slack.com/ or any other platform which has integration with Github as a hub for the community.

For chat, you might want to check out [Gitter](https://gitter.im/) and compare it with Slack. I run a couple of Slack chatrooms, and it's a bit challenging to add new people on open projects. I think that Gitter might be more friendly for public-facing projects where Slack is good for internal communication.

**Comment by synkarius** [comment]
@j127 You're contributing already! :-) I had no idea Gitter existed. After comparing it with Slack, I think I agree with your evaluation about public and private projects. 

@Zone22 Good call about leaving this place just for issues.
